### ISSUE TITLE
Awesomewm will not boot

### ISSUE THREAD

**Issue by floofywoofles** [archlinux/archinstall#1026]
archinstall creates an xsession, but does not boot to awesomewm.

Using latest arch iso.

**Comment by Torxed** [comment]
This is by design and not a bug.
You have to run `startx` to start awesome (it's pre-configured for xinit).

There's no [smooth way](https://wiki.archlinux.org/title/awesome#Autostart) of auto-starting it, and there's really no greeter that is endorsed. Although lightdm is mentioned.

If this really is desired (I think most people just use xinit and run startx), then I'd welcome a PR that cleanly autostarts awesome without too much sed/find-and-replace logic in text files as it gets wonky real fast.
