### ISSUE TITLE
Default partitioning results in tiny root parition

### ISSUE THREAD

**Issue by fsimonis** [archlinux/archinstall#1040]
**Problem description**

I used `archinstall` shipped with the latest live ISO (Release: 2022.03.01) to install Arch (duh) on a 500GB drive.
I used the automatic partitioning option and chose not to encrypt my home partition.

The resulting partitioning was:

size | partition
--- | ---
484M | EFI
34.4G | `/`
430.9G | `/home`

My root partition filled up pretty quickly due to libvirt images, docker images and system-wide flatpaks.

**Expected result**

The root partition should have been bigger. Especially as the home partition was gigantic in comparison.

**Proposition**

The automatic partitioning should try to provide a non-problematic setup by default.

Option 1) always go for a single partition including both home and root.

size | partition
--- | ---
484M | EFI
465.3G | `/`

Option 2) Use 100 GB for `/` and what's left for `/home`. Use a single partition if the drive is < 250GB.

size | partition
--- | ---
484M | EFI
34.4G | `/`
430.9G | `/home`

**Comment by hexarch** [comment]
See https://github.com/archlinux/archinstall/issues/1024
This is being fixed in next release.

**Comment by fsimonis** [comment]
Great!
Thanks for this awesome project!

**Comment by wllacer** [comment]
@fsimonis  Thanks for your input. Without knowing what the users want/need is difficult to get something useful.
There is a thing inherent to a default setup ... it will be always problematic for at least one non empty subset of users ;-)
Just to document it for further reference ... My vision for this is rather having a couple of "standard use case layouts" rather than a single default option, so your case is very interesting-

_There is at least one other posible layout_: From the description of your workload, it seems that you need above all a sizable `/var` subtree, rather than  general root space (Docker, libvirt, and flatpack images you cite all end up by default there) . Like it happens to heavy DB users (like me at times). So perhaps something like (numbers just  _order of_ magnitudes)

size | partition
-- | --
512MiB | EFI
32 GiB | /
224 GiB | /home
224 GiB | /var

could be a more adequate match for your needs and similar. I'd add up a `swap` partition (discussion for other day).  And probably `/home` would still be overdimensioned

32 GiB for `/` without `/var` is, for most uses, size enough. I reckon that 64 GiB; for an unified `/` + `/var`, if only sparsely using VMs -VirtualBox not included-  or databases; would give a lot of headroom for most users (unless you are a compulsory tester of new things and never uninstall, or never clean up the pacman cache). My experience with 32 in this case, is, that after a (german) couple of years it needs regular cleanup (which is not bad in itself).

There is a fourth option, consider moving to btrfs with subvolumes. The default layout now, doesn't either cover exactly your needs, but it is not difficult to change. Requires some study and mental adaptation but, at least in my case, it has provided a lot of additional flexibility to the classical way.

And to end, just an off-topic question. You mentioned flatpack images. I might be an "old fashioned hat", but worked on the assumption that this fad was peripherical to the Arch "viewership" If i might ask, what and why are you running from flatpacks instead of distribution packages ?

**Comment by fsimonis** [comment]
> My vision for this is rather having a couple of "standard use case layouts" rather than a single default option, so your case is very interesting

This sounds like a very good approach. :+1:

> And to end, just an off-topic question. You mentioned flatpak images. I might be an "old fashioned hat", but worked on the assumption that this fad was peripherical to the Arch "viewership" If i might ask, what and why are you running from flatpaks instead of distribution packages ?

I am working with vtk files in daily development. I require the [vtk](https://archlinux.org/packages/community/x86_64/vtk/) library as a dependency and [Paraview](https://archlinux.org/packages/community/x86_64/paraview/) to visualize the results.
Both packages are conflicting each other for some reason, so I install the vtk library from the repo and get the Paraview application as a flatpak. It costs me a few GiB of storage but it "just works".

I have been pondering about this partitioning scheme for a while now and the big home directory could actually be the right default choice for the normal user.
User-installed flatpaks are stored in the home directory instead of the system directory, which will grow as more application developers choose to distribute their applications primarily using flatpak. Development schemes also move(d) to project local scopes such as python/ruby virtual environments, bundler, npm, or even [spack](https://spack.io/). So, the size of the home directory will become increasingly important.
Anyhow, just some food for thought.

**Comment by svartkanin** [comment]
I think this is fixed
