### ISSUE TITLE
Feature request & questions

### ISSUE THREAD

**Issue by yscitto88** [archlinux/archinstall#105]
Hey there,

i use Arch Linux since many years and a few days ago I came across this project. Today I took a closer look and have a few more questions and a few feature requests.

**Feature requests**
- Add more documentaion
  - The ["unattended" example](https://github.com/Torxed/archinstall/blob/master/examples/unattended.py) is in my opion a little bit to undocumented
- Add support for swap and LVM
  - i have the following Partition scheme and want to use it with archinstall (if it's possible)
```
NAME            MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
nvme0n1         259:0    0 465,8G  0 disk  
├─nvme0n1p1     259:1    0   512M  0 part  /boot
└─nvme0n1p2     259:2    0 465,3G  0 part  
  └─main        254:0    0 465,2G  0 crypt 
    ├─main-swap 254:1    0     8G  0 lvm   [SWAP]
    └─main-root 254:2    0 457,2G  0 lvm   /
```

**Questions**
- Is it possible to choose between grub, syslinux and systemd-boot?
- Which parameter are used for the disk encryption? Can they be customized?
- In the [minmal example](https://github.com/Torxed/archinstall/blob/master/examples/minimal.py): becomes the user "anton" the password "test" or "root"?

I like this project and i want to use it in the future but i'm not very familiar with Python.
\
\
FYI: [archlinux.life](https://archlinux.life/) is down

**Comment by Torxed** [comment]
Hi, glad you found it! :D

Regarding documentation, you're 100% correct, this needs a big update.
Currently the man-page as well as the official documentation describing the [guided](https://archinstall.readthedocs.io/en/latest/installing/guided.html) installation is pretty decent. I would like to extend that documentation to cover the unattended as well.

In terms of swap and LVM, there's really two main issues (features) tracking this: #46 & #51.
Both those are the highest priority right now, enabling more complex partition schemes.
Since the Arch community is more tech savvy and care more about these kinds of things, making an installer that can fit all needs will be virtually impossible as people experiment with all kinds of things *(#99, #93, #90, #89 and so on)*.
So the first step towards enabling this - will be to support skipping the formatting step and use existing partition tables :)

----

Q1: Current not, `systemd-boot` is hard coded for now, but in line with #51 *(and BIOS support)* this is the second highest priority right now after the partitioning.
Q2: They will be customized, but for now they're pretty hard coded sadly because I had to stick to one installation method in order to sync everything else - so this is the current method: 
 * LUKS2
 * argon2i
 * sha512
 * key-size 512
 * iter-time 10000
 * using urandom and luksFormat
Again, since the formatting (and in partial the encryption) will support current setups rather than wiping the drive, I hope that this opens up for more complex setups and instead just guiding through the tools/generics a bit faster :)
Q3: So the following:
```python
installation.user_create('anton', 'test')
installation.user_set_pw('root', 'toor')
```
Could be translated to:
```python
installation.user_create('anton', password='test')
installation.user_set_pw('root', password='toor')
```
So the user will be `anton` with the password `test` and `root` will have the password `toor`.
This profile has more served as a example of how to script your own installations.
If this profile will be actively used, that user-setup should probably be removed and a forced user creation should be added.

Thanks for the ping on the domain, I have to reset it manually every now and then.

**Comment by xelnagamex** [comment]
Guys, is anyone already working on ability to install on lvm?

**Comment by Torxed** [comment]
> Guys, is anyone already working on ability of installing on lvm?

Sorry for the late reply, been caught up in some private stuff.
The other day I re-wrote a large portion of the partitioning logic, my goal is to start on btrfs subvolumes after that's stable enough and then lvm. Getting this right will probably take some time - as I don't want to be left with something that works without encryption but not with for instance. But the goal is to support the most common partition/disk setups : )

**Comment by Torxed** [comment]
> F2FS

I don't see why not, I'm not an expert on F2FS but I can't find any drawbacks on adding this.
Feel free to submit a PR with the necessary [flags](https://wiki.archlinux.org/title/F2FS#Compression), or we'll get around to it once we can. I'm currently knee deep in partitioning logic and get the `master` branch up to working condition for release.

**Comment by Torxed** [comment]
I’ll go ahead and close this as most if the functionality and requests have been implemented or addressed. The documentation is almost always in dire need of update so that’s probably the last thing we haven’t done in this issue, but it’s always in the back of our minds :)
Thank you for some good suggestions, and they should all be there in v2.3.1 which was released last week.

**Comment by sheepymeh** [comment]
Will it be possible to change the encryption parameters in the new update? I am especially interested in iter_time as having it set to 10000 makes the boot time much longer.

**Comment by Torxed** [comment]
I’ll include it in #953
