### ISSUE TITLE
Add Cloudflare mirrors as an option

### ISSUE THREAD

**Issue by matteoturini** [archlinux/archinstall#1051]
Cloudflare mirrors (https://cloudflaremirrors.com/) are super fast mirrors served by Cloudflare. I don't know the feasability of adding this and 5 parallel downloads as an option is, but that seems pretty good.

I get consistent 50-80MB/s using this mirror instead of 15MB/s using other mirrors. And it's localized to the user's country.

**Comment by Torxed** [comment]
You should be able to directly write the mirror server URL in the mirror selection step. and it should use it instead of the official mirrors :)

**Comment by svartkanin** [comment]
@Torxed where is that input field? I thought for mirror selection we only have the predefined ones, basically the countries?

**Comment by Torxed** [comment]
![screenshot](https://user-images.githubusercontent.com/861439/160834363-975bb60e-960e-4644-be43-183c0ecbd315.jpg)

Free text ftw : )

**Comment by matteoturini** [comment]
This is something that should be written here

"by number or full name" should be "by number, full name, or URL"

And possibly adding the Cloudflare mirror to this selection.

**Comment by svartkanin** [comment]
@Torxed yeah this is a regression since we're only displaying options now in the new menu. I'll have a look at this one.

**Comment by Torxed** [comment]
> And possibly adding the Cloudflare mirror to this selection.

To avoid maintaining a separate list, we use whatever upstream has.
This is to have a uniform list of mirrors. The best thing you could do is petition to have it on the official record instead of [unofficial mirror](https://wiki.archlinux.org/title/Unofficial_mirrors#Worldwide) :)

> This is something that should be written here

I agree that the language could have been better formulated.
But the intent is that majority of users should use the official mirrors anyway.
The new menu system allows us to be a bit more flexible, and it looks like @svartkanin is on it! :D

**Comment by matteoturini** [comment]
Thanks for your replies.

> The new menu system allows us to be a bit more flexible, and it looks like @svartkanin is on it! :D
High hopes for the new menu system!

**Comment by matteoturini** [comment]
Closing as Cloudflare is unofficial mirror, and archinstall merely fetches upstream mirrors.

**Comment by svartkanin** [comment]
We'll still fix the regression though so it is going to be possible to add custom mirrors
