### ISSUE TITLE
the reflector select wrong mirror

### ISSUE THREAD

**Issue by heheda123123** [archlinux/archinstall#1147]
Is there any method to disable the rank mirror stage(reflector service). It always select the slow mirror.
I want manully edit the `/etc/pacman.d/mirror` file and keep use it.

**Comment by Torxed** [comment]
The reflector service is a service that comes default with the ISO and doesn't have much to do with archinstall.
However, if you want to use a specific mirror - I would suggest waiting for it to complete after booting the ISO and before running `archinstall`, you can just manually edit `/etc/pacman.d/mirrorlist` and then run `archinstall` but skip the mirror region step.

I'll close the ticket because I'm pretty confident the above will solve your issue.
If that's not the case just drop a comment and I'll re-open this ticket :)

**Comment by heheda123123** [comment]
Will archinstall modify the mirror during execution?
After I disable and stop the reflector service, execute archinstall, and a rank mirror will be output during the execution. The file /etc/pacman.d/mirror will still be modified.
Maybe my question needs to be described differently. Will archinstall modify the file /etc/pacman.d/mirror? Can this step be skipped?

**Comment by Torxed** [comment]
It will not, if you skip any step - it should perform no action.
The tricky thing might be that there are services and stuff in the ISO itself that are "out of our control" that might be confusing to some.

If `/etc/pacman.d/mirrorlist` is modified, that is a bug :)

**Comment by heheda123123** [comment]
Thank you, I will take a closer look and ask again if I encounter problems
