### ISSUE TITLE
Too many partitions ?

### ISSUE THREAD

**Issue by cutix65** [archlinux/archinstall#1148]
Something goes wrong with too many partitions ? I have set up /mnt/boot to partition #1 and /mnt to partition #7 (almost 30G free and available). Sorry for the too many partitions; mine is a Company PC with WinZozz and I have several Linux distros on board ;)

It ends with no space ?!?
Pls see attached log
[install.log](https://github.com/archlinux/archinstall/files/8649568/install.log)

**Comment by Torxed** [comment]
Hi.

The amount is fine, but the mountpoint are wrong. They should be relative *inside* the installation, not absolute paths.
So:
```json
{
    "ESP": true,
    "PARTUUID": "e0a405ab-e1d8-4749-8923-0b92898e720e",
    "boot": true,
    "encrypted": false,
    "filesystem": {
        "format": "vfat"
    },
    "mountpoint": "/mnt/boot",
    "size": 616448,
    "start": 2048,
    "type": "primary",
    "wipe": false
}
```
Should be:
```json
{
    "ESP": true,
    "PARTUUID": "e0a405ab-e1d8-4749-8923-0b92898e720e",
    "boot": true,
    "encrypted": false,
    "filesystem": {
        "format": "vfat"
    },
    "mountpoint": "/boot",
    "size": 616448,
    "start": 2048,
    "type": "primary",
    "wipe": false
}
```

This is because `archinstall` defines where to actually mount them, which is `/mnt/archinstall` and not `/mnt`. This is to avoid issues with accidentally mounting things to `/mnt` and we don't want to risk wiping or destroying manual stuff.
