### ISSUE TITLE
add menu for selecting display manager

### ISSUE THREAD

**Issue by zlianon** [archlinux/archinstall#1154]
It would be convenient if the desktop profiles offered the ability to choose a display manager.
Currently that is locked in to the profiles, even even tho post-configuration can be done to change this quite easily, it would be beneficial to be able to change the option before the installation is complete.

**Comment by Torxed** [comment]
Could you elaborate with a description? :)

**Comment by zlianon** [comment]
e.g. i3 profile forces lightdm installation, it would be good to offer alternatives

**Comment by Torxed** [comment]
I updated the description as to what I think you wish for.
I also made the argument for you why this would be a good thing.

This has historically not been in scope because it can be considered post-installation configuration.
And some people would surely argue that it's good enough to have something working and tweak it.

Which is why I'll leave this issue open for a while, to see what the general consensus is so we can discuss it :)

**Comment by svartkanin** [comment]
@Torxed we can close this as it should be resolved with the new profile manger
