### ISSUE TITLE
Guided installation doesn't detect if it doesn't have root privileges

### ISSUE THREAD

**Issue by diogenes0** [archlinux/archinstall#116]
I ran the guided installation in userspace on my computer to install Arch on a USB drive. I got fairly far in the installation process before getting the following error "PermissionError: [Errno 13] Permission denied: '/var/log/archinstall'". If the guided installer isn't invoked as root, it should detect that as soon as it's launched. It should then either exit or invoke sudo to get root privileges.

**Comment by Torxed** [comment]
Nicely spotted! That's an oversight since introducing the `/var/log/archinstall` log placement, it used to be placed in `~/.cache/archinstall` but moved to `/var/log/archinstall` for a more traditional location.

I'll see which road we'll take, if we'll omit the `/var/log/archinstall` placement only if we don't have permission, or if we should require root privileges all together and warn early on. Because I don't think strictly speaking the installation itself requires root, and I think I used to install in a loopdev without root (but perhaps I just ran it as sudo out of habbit back when I tested).

Anyway, we'll have this sorted out! : )

**Comment by Torxed** [comment]
The error should be fixed in [master](https://github.com/Torxed/archinstall/tree/master) now.
I still don't know if you're able to install Arch without root, I'm afraid that pacstrap etc might have some permission errors in the installed medium.

Once the next release comes out you should be able to test this, unless I manage to get around to it against master (instead of release versions).

**Comment by dylanmtaylor** [comment]
This could probably be closed if it's fixed in master @Torxed
