### ISSUE TITLE
"Create a required super-user with sudo privileges" should allow me to go back

### ISSUE THREAD

**Issue by kpcyrd** [archlinux/archinstall#129]
If I don't provide a root password I'm asked to create a user. If I change my mind because I don't want to create an user I can currently only exit the application and start over.

Tested with 2.1.3-1

**Comment by Torxed** [comment]
This was partially a design choice, to avoid complex menu jumps back and fourth.
However the user-section would be a simple implementation to group up and create a "You did not create a super-user account" and then return to the root question, since they're so close to each other both code wise and logic wise.

**Comment by dylanmtaylor** [comment]
what if we have an option to enter 'root' to specify a root password if the user didn't set one (during user creation)?

**Comment by Torxed** [comment]
> what if we have an option to enter 'root' to specify a root password if the user didn't set one (during user creation)?

Maybe we re-work the user creation loop into a single loop, with a menu + submenu (I love how this sounds like I'm talking about the future, but it's so 1990's).. Where the user gets three options:
```
 0: Set a root password
 1: Create a user
 2: Create a super-user
 ```
 And we simply check if one of those are fullfilled?

**Comment by Torxed** [comment]
This has been implemented in master :) thank you for the suggestion!
