### ISSUE TITLE
Multilib-testing enabled by default

### ISSUE THREAD

**Issue by Nuxmin** [archlinux/archinstall#1317]
Hey there!

I think this has been a bug for a while. Every time you do an installation, when you select to enable the multilib repo, the installer also enables multilib-testing.

I can provide a log file in case it's needed but it's pretty straightforward. This makes the system unstable by default because you get packages from both multilib and multilib-testing.

**Comment by dylanmtaylor** [comment]
Great catch, I think we need to rework the logic to select the additional repositories.

**Comment by 0xShree** [comment]
Hi 👋
The problem is in the regex expression

https://github.com/archlinux/archinstall/blob/a7ca037a26de53fd242f89bc6a90fd53337b4d13/archinstall/lib/installer.py#L328

Here is an example

![image](https://user-images.githubusercontent.com/49250702/177372873-19448699-42f6-43a4-a6a5-68e81d7408ac.png)

In that regex expression period `.` at the end of `multilib` string can be removed as there is no character to be matched between `multilib` and closed square bracket `]`

![image](https://user-images.githubusercontent.com/49250702/177373892-17cd5ab7-6212-48c6-abe3-0a80a222ea25.png)

**Comment by dylanmtaylor** [comment]
> Hi 👋 The problem is in the regex expression
> 
> https://github.com/archlinux/archinstall/blob/a7ca037a26de53fd242f89bc6a90fd53337b4d13/archinstall/lib/installer.py#L328
> 
> Here is an example
> 
> ![image](https://user-images.githubusercontent.com/49250702/177372873-19448699-42f6-43a4-a6a5-68e81d7408ac.png)
> 
> In that regex expression period `.` at the end of `multilib` string can be removed as there are no characters to be matched between `multilib` and closed square bracket `]`
> 
> ![image](https://user-images.githubusercontent.com/49250702/177373892-17cd5ab7-6212-48c6-abe3-0a80a222ea25.png)

Please feel free to open a PR if you want the credit for debugging this

**Comment by 0xShree** [comment]
yeah sure, this will be my first contribution wohoo 🥳

**Comment by c3l3si4n** [comment]
This issue is definitely real. My last update failed due to an issue with multilib-testing being enabled on a system installed with archinstall. It's relieving to see that the pull request was already opened. Thx! :heart:

**Comment by ak1ra26** [comment]
Same problem. I have this:
warning: cannot resolve "alsa-lib=1.2.7", a dependency of "lib32-alsa-lib"

**Comment by DudeDude2** [comment]
How do I safely remove multilib-testing? Do I just comment it in pacman.conf or are there more steps involved?
I only play League of Legends so I don't think I need multilib-testing.
