### ISSUE TITLE
archinstall crashed when dealing with partitions upon install

### ISSUE THREAD

**Issue by oMoMa** [archlinux/archinstall#1319]
[install.log](https://github.com/archlinux/archinstall/files/8864941/install.log)

**Comment by Torxed** [comment]
Thank you for reporting the issue and all we usually need is the install log which you correctly attached :) For future references the instructions are here: https://archinstall.readthedocs.io/help/issues.html but it should also be in a issue template format :)

Regarding your issue, I did not see a `/boot` mountpoint? (I'm on the phone and might have missed it, if so I do apologize!).
Lastly you would have to also mark the `/` partition for wiping, otherwise we don't dare to wipe it via guessing i'm afraid.

When those two corrections are made, make sure no other partitions was set for encryption or wiping (as those are destructive instructions)

**Comment by oMoMa** [comment]
Thank you for the detailed response.
I actually didn't stop fiddling around with it last night. I did remember at some point to declare mounting points for _/boot_ and _/_ , however that wasn't the only case.

I cloned the latest code for testing as per instructions in the readme file. The errors were a little different this time (yet it was much more polished. Thank you for your great work).

I also started reading other closed and open issues for similar behavior and found two culprits. _Swap_ option, and using _**ventoy**_ . Disabling the swap option didn't help but directly writing the image onto the flash drive instead of ventoy did the trick. The script finished it's job.

Unfortunately, however, It didn't boot after a restart. Saying "/new_root" could not be mounted as it wasn't found or something. I just gave up at that time.

**Comment by oMoMa** [comment]
I want to give update on the situation. I tried archinstall in vm with similar configurations and it worked so I decided to reinstall this thing since I couldn't resolve the mounting issue I described above.
Now I'm getting another error. I'll provide logs once I boot the device.
The error seems to be "Failed to convert PARTUUID * to a partition index number on blockdevice /dev/nvme0n1

The problem is, that PARTUUID doesn't even exist when I run blkid.
Where is it getting that from?
![IMG_20220609_152612.jpg](https://user-images.githubusercontent.com/70336271/172831272-d1f5dfef-70a3-4d8e-9683-6b78ad62eca7.jpg)

**Comment by svartkanin** [comment]
@Torxed I think this is also resolved with the partition changes :)

**Comment by Torxed** [comment]
Yea, I introduced some additional tweaks the last two weeks that should solve this.
I still do find this particular issue from time to time. But it's extremely hard to trigger - so I've added some debug information that should help.

It happens when internal timers conflict in disk operations, so it's going to be rare - but might happen.
