### ISSUE TITLE
Could not get PARTUUID for /Dev/sdxY using blkid / Failed to convert PARTUUID to partition index

### ISSUE THREAD

**Issue by arcolinuxz** [archlinux/archinstall#1371]
Using this beta build

https://github.com/archlinux/archinstall/actions/runs/2608752104

I got a failed installation.

Submitting the error to see if it can assist you making the code better

![ArcoLinux-2022-07-11_08-38](https://user-images.githubusercontent.com/36679406/178203493-b2ab4a2c-2e64-4788-b05e-2af762d2a14d.png)

and here is the video I was making at the time (hidden on youtube) - in video a journalctl that does not show much I believe - but you can check

https://youtu.be/OGtkz5MTE3A

**Comment by arcolinuxz** [comment]
Tried it via pip update

same or similar result

https://youtu.be/tZfW657yi5g

**Comment by wllacer** [comment]
If you are using the master branch (or similar) this is the same error as in issue #1343 . It is solved via PR #1355, which is in the integration queue

**Comment by arcolinuxz** [comment]
if you can leave a message when it is incorporated

I can donate time to test it out

😀

**Comment by Phil995511** [comment]
I have the same problem with the 2022.08.05 ISO of Arch Linux.

It's impossible to make a installation by Archinstall :-(

**Comment by Torxed** [comment]
I'll have a look at it, but it's hard to recreate these.
I have none of these issues on over 100 installations. I'm not saying that it doesn't happen - just that dear lord it's hard to trigger it so I can get the correct debug output.

**Comment by Phil995511** [comment]
> I'll have a look at it, but it's hard to recreate these. I have none of these issues on over 100 installations. I'm not saying that it doesn't happen - just that dear lord it's hard to trigger it so I can get the correct debug output.

Thank you, the installation worked perfectly with Archinstall on archlinux-2022.06.01-x86_64.iso but it no longer works with archlinux-2022.08.05-x86_64.iso.

The machine concerned by this problem is a Dell 9570 with an Intel Wi-Fi 6E AX210 card on board and connected by USB to a Sharkoon USB 3.0 Hub with RJ-45 Lan Ethernet Adapter at 1 Gb/s.

**Comment by Torxed** [comment]
@arcolinuxz do you know if you're using KVM or Qemu as the virtualization backend? If it's qemu could you export the qemu startup string? This would help me simulate the hardware setup in a way that best represent the state where you have issues.

@Phil995511 Unfortunately this issue has been coming and going, and I could almost bet you my lunch box that "the next ISO will work", as it's a random hardware (disk) issue that happens some times - but not 100% of the times. And it could be kernel versions dealing with SATA setups differently and what not. So a qemu scenario would be nice to simulate the issue :)

With that said, the feedback is very valuable and I do appreciate it. Because I can look up that laptop specs and what SATA controller they're using etc.

**Comment by Phil995511** [comment]
> @Phil995511 Unfortunately this issue has been coming and going, and I could almost bet you my lunch box that "the next ISO will work", as it's a random hardware (disk) issue that happens some times - but not 100% of the times. And it could be kernel versions dealing with SATA setups differently and what not. So a qemu scenario would be nice to simulate the issue :)
> 
> With that said, the feedback is very valuable and I do appreciate it. Because I can look up that laptop specs and what SATA controller they're using etc.

I have done some more tests, but there is nothing to do. Even with version 22.06.01 archinstall can no longer see the necessary mirrors on the internet to realise its installation.

But it was working a few weeks ago. Since Dell updated the bios of my Laptop is this the reason for this failure??

Best regards.

**Comment by Phil995511** [comment]
@Torxed Thank you for your good advice, in the end my problem is only related to https://github.com/archlinux/archinstall/issues/1389#issuecomment-1233288759 

I hope you manage to stabilize this situation because it is extremely difficult to have to use an installer that only works sometimes...

After being a Mandrake > Suse > Mint > Debian user, I am now considering migrating to a rolling release type operating system to maximize the security of my system, which is why I am testing Arch. But if it's so complicated to install, it might be difficult for me to adopt it.

If you allow some criticism based on my experience :

- It lacks a graphical installer, it is not easy for me to choose the Arch installation disk and his partitions on my system which is equipped with 5 hard disks divided into 9 partitions.

- ntfs-3g dkms man pamac and maybe Yay should be provided as standard.

- Installing Cinnamon via archinstall should include more base software and missing start menu icons should be added.

Thank you for your help, wishing you the best possible future.

**Comment by Torxed** [comment]
> I hope you manage to stabilize this situation because it is extremely difficult to have to use an installer that only works sometimes...

@Phil995511 I get that frustration. Sadly, we're in mercy of the upper Arch Linux gods as well. As it's a human + systematic issue of key management. Just like `chromium` or `pacman` would stop working if you the user doesn't update the certificates in time for instance. We **try** very hard to ease over this hump by updating the keys for you - but the underlaying issue change from time to time.

Usually it's the keys for individual packages that are out of date, so installing say `nano` won't work.
This time it was the keyring itself that had an invalid signature causing a moment-22.. And so we couldn't update `archlinux-keyring` since we didn't trust it :package: 

---

These types of issues happens once every 2 years or so, or used to. So the downside of using a rolling release was \*meh*, you could live with it. But for some reason this key issue has been happening a lot lately.

---

I welcome criticism, just keep in mind that we're an application - just like anyone else. We just happen to be packaged on the official ISO. So some criticism will be more like preaching to the quire :)

> It lacks a graphical installer

I tried making one - https://github.com/Torxed/archinstall_gui but lack of time caused me to put that on the freezer.
Also getting that officially signed will be harder I think. Because it requires a HUGE overhaul to the existing quite small ISO.

> ntfs-3g dkms man pamac and maybe Yay should be provided as standard.

`ntfs-3g` is note required since NTFS has read+write support in kernel since v5.15.
`dkms` gets installed when needed, but not otherwise. And it's strictly not needed to get something up and running, you can add that post-installation without issues.

Regarding `yay`, that's a strict policy from the Arch Linux staff/support/community that it should never be supported, so adding it would detach us politically from ever being supported outselves.. Meaning we'd be shooting ourselves in the foot and be kicked out. So can't do, but we have plugins such as [archinstall-aur](https://github.com/Torxed/archinstall-aur) that you can source with `--plugin` and then `additional packages` work across AUR as well. I get it, not as smooth, but that's what you'll get until you manage to convince the whole machinery to support AUR packages (tl;dr: we share your pain)

> Installing Cinnamon via archinstall should include more base software and missing start menu icons should be added.

Feel free to submit a PR for this. We keep things simple as it usually causes more divide trying to "force" something.
This is the reason why most of our things are perhaps - from a wider use base perspective - a bit too minimalist. But it's what we have been able to get away with without awakening endless debates :)

---

Wish you all the best too, and thank you for taking the time to leave feedback! We listen, and we try!

**Comment by Torxed** [comment]
@arcolinuxz I think this is fixed, by tweaking a `sleep` into a better position in the code.
However, it does still happen. I went from getting 1/5 installations to 1/100 roughly.

It's still weird when it happens but I'll consider this closed as it's a race condition with the hardware.
If this happens again in the next release, we have some more debug information that would be valuable to debug this and perhaps fix it for good. Also if you could provide the `qemu` startup string I'd be happy to debug this further, it would help emulate your setup.

**Comment by Phil995511** [comment]
Hello Anton,

I answer you a bit late...

I just redid a virtualized installation of Arch. I attach below a screenshot showing you that the man command is not installed by default ;-(

[http://image.noelshack.com/fichiers/2022/40/5/1665171617-capture-d-ecran-du-2022-10-07-21-05-15.png
](url)

I also had problems with an NTFS USB stick not being recognized without ntfs-3g which I had to add by hand for that.

Arch is also installed on my laptop's ssd and I'd probably like to completely migrate from Debian to an Arch system on my workstation as well.

What I miss the most as software available in native Arch is above all and above all Paman which greatly simplifies the administration of a system !! It would be so nice to make it natively available to us :)

Being able to benefit from Archinstall is already very good, but a graphical solution on top of that would be really something necessary for me too. To install Arch on the right partitions and the right disks, being sure not to make any mistakes and to be sure not to overwrite my /home in the event of a reinstallation (which I have not yet succeeded in doing with Archinstall ), I need a graphical installer like Calamares which is easy to integrate it seems and performs well.

About Cinnamon you tell me to do a PR for it can you tell me more about it ?

Thank you for all you do for us, best regards.

Philippe

**Comment by Phil995511** [comment]
Hello Anton,

I answer you a bit late...

I just redid a virtualized installation of Arch. Here is attached a
screenshot showing you that the man command is not installed by default ;-(

Arch is also installed on my laptop's ssd and I'd probably like to
completely migrate from Debian to an Arch system on my workstation as well.

What I miss the most as software available in native Arch is above all and
above all Paman which greatly simplifies the administration of a system
!! It would be so nice to make it natively available to us :)

Being able to benefit from Archinstall is already very good, but a
graphical solution on top of that would be really something necessary for
me too. To install Arch on the right partitions and the right disks, being
sure not to make any mistakes and to be sure not to overwrite my /home in
the event of a reinstallation (which I have not yet succeeded in doing with
Archinstall ), I need a graphical installer like Calamares which is easy to
integrate it seems and performs well.

Thank you for all you do for us, best regards.

Philippe


Le lun. 5 sept. 2022 à 12:18, Anton Hvornum ***@***.***> a
écrit :
