### ISSUE TITLE
Ask unencrypted or encrypted destination install.  Also ask what filesystem for destination install.

### ISSUE THREAD

**Issue by omac777** [archlinux/archinstall#139]
I read minimal.py

https://github.com/Torxed/archinstall/blob/2c90f02b6b26cc489e90f7536fe8931a4b2b9195/examples/minimal.py#L9
It implies everybody wants an encrypted disk when installing which is not the case.
Please ask the user whether they wish to encrypt the destination drive or not.
If they do not wish to encrypt, then don't use a password.

https://github.com/Torxed/archinstall/blob/2c90f02b6b26cc489e90f7536fe8931a4b2b9195/examples/minimal.py#L13
Also please ask the user what filesystem to format the destination disk? 
The current default for use_entire_disk() is 'ext4',
https://github.com/Torxed/archinstall/blob/2c90f02b6b26cc489e90f7536fe8931a4b2b9195/archinstall/lib/disk.py#L445
but fedora rawhide's current default has recently changed to 'btrfs' now.
I would recommend you offer up both 'ext4' and 'btrfs' in a list, and change your default to 'btrfs' also.

Thank you for listening.

**Comment by Torxed** [comment]
Regarding minimal, it's just shipped as an example and was not meant to be the main thing people used. And guided.py offered the same minimal experience but with the input you're mentioning, such as choosing file type or disk encryption.
It's also inherited from legacy examples which I really should update - and since the repo has become more popular I really welcome feedback on these types of things as it might even be used more and more.

But the guided installer is the default that's started through the arch package [archinstall](https://archlinux.org/packages/extra/any/archinstall/).

With that said, I do agree with you and I think the minimal should be re-visited and at the very least ask the user for "breaking changes" such as selecting the drive. Now that I've brought back `python x --disk=/dev/sda` parameters to archinstall, this could be done through `archinstall.arguments.get("disk")` :)

**Comment by svartkanin** [comment]
@Torxed we can close this as with all the reworks and new menu this should be covered as well

**Comment by svartkanin** [comment]
This is available in the latest version
