### ISSUE TITLE
When choose NVIDIA proprietary driver, the system can't start

### ISSUE THREAD

**Issue by NyaDoo** [archlinux/archinstall#1395]
I use Gigabyte aero 15 OLED XD notebook with Intel 11800h and 3070 graphics cards.
When I choose the open source kernel driver, I can enter the system, but sleep can't work (I can't wake up again after sleep, so I can only force shutdown and restart).
When I choose a proprietary driver, I can't enter the system. I'll be stuck with only one _ in the black screen interface of the symbol, the symbol will not flash, and any keys will not work, including ctrl+alt+f3.

**Comment by felipeolliveira** [comment]
I have a Legion 5i laptop with RTX 3060 and I have the same problem!

**Comment by Torxed** [comment]
Have both of you followed https://wiki.archlinux.org/title/Hybrid_graphics post-installation? Because dual graphics card, especially in laptops where they call them "Hybrid graphics" is a bit of a PITA some times. Nothing we really configure or prepare for in archinstall other than install the drivers you select.

**Comment by felipeolliveira** [comment]
I didn't follow any post installation. I had a Legion 5i with RTX 2060 that worked perfectly after installing it with archinstall. I didn't know it had specific settings.

**Comment by felipeolliveira** [comment]
I read the documentation and was able to at least deliver video through the processor's integrated GPU. I will continue in the documentation and I believe I will have no problems

**Comment by felipeolliveira** [comment]
Apparently it's a kernel issue as of 5.18 with current Nvidia drivers.
I ended up downgrading to lts version, 5.15 and the problem was solved

There is another solution that is performed during grub boot, but I chose to use an lts kernel anyway

https://github.com/NVIDIA/open-gpu-kernel-modules/issues/256

**Comment by Torxed** [comment]
I'll close this issue since there's not much we can do in that case.
Also the open driver is in a bit of an experimental stage so this probably won't be the last issue surrounding it :)
