### ISSUE TITLE
Better description what buttons u can use with the script.

### ISSUE THREAD

**Issue by eskiq** [archlinux/archinstall#1436]
There is no information about space for checking boxes. Also when someone will try to set for example more than 1 mirror region while in search mode gl to him. I just figure out that I can press TAB to check boxes in search mode. Better description would help.

**Comment by Torxed** [comment]
I think this should go into the `man` page or `--help` if anywhere.
The menu system is getting quite full of text as it is IMHO. Would that be good enough?

**Comment by eskiq** [comment]
I think that not everybody is using man pages or project pages to check basic stuff like this while script is already loaded. There is already partial legend but not full. Man page for archinstall is really long. Maybe it would be good to add a line to the beginning of the script with basic information of how to use this script containing a link to man page for further information.

The other and probably a better way to improve things would be by using more info in the same line. So for example instead of:

Use ESC to skip
Use CTRL+C to reset current selection

something like this with color:
[ESC](#) to skip &ensp; [CTRL+C ](#) to reset current selection

That would make it look more compact and there is still place to add for ex. SPACE and TAB in search mode if those options could be used.

I would also change skip to something different like maybe 'go back' or 'main menu'

BTW I shouldn't wrote it here but when I use ESC for skip in Drive(s) it would go outside of the script. Any other option with skip is working correctly but not this one.

**Comment by Torxed** [comment]
> Maybe it would be good to add a line to the beginning of the script with basic information of how to use this script containing a link to man page for further information.

I'm personally quite against this. I want to keep the installer to a workflow that is non-interruptive. It's already a bit of a PITA that the user creation isn't set to sudo by default and that you need to jump down to "confirm" instead of being set to the username. It's small stuff, but overall it creates a bit of friction and frustration.
Adding a welcome screen will only be useful once, but will be there always - if that makes sense.

> something like this with color:
> [ESC](https://github.com/archlinux/archinstall/issues/1436#) to skip [CTRL+C ](https://github.com/archlinux/archinstall/issues/1436#)to reset current selection

That could work, but again. It would only be useful once and after that it just takes up space :)

Lets try it and see, maybe I'm wrong.
But I personally don't have the time to submit such a PR as there's more pressing things. Like updating the `man` and `--help` pages that you pointed out is way to long hehe.

> BTW I shouldn't wrote it here but when I use ESC for skip in Drive(s) it would go outside of the script. Any other option with skip is working correctly but not this one.

I think this is a known issue, but I'll see if we have a ticket otherwise I'll create one.

**Comment by eskiq** [comment]
> It's already a bit of a PITA that the user creation isn't set to sudo by default

I was wondering about it yesterday why it's like that in the first place.

Even small legend on front page of the project would help. I was just lucky to figure out that Tab will check box while in search mode. Others need to suffer or read man page that is probably already having a few hundreds of lines.

Thanks for looking into those problems/improvements.
