### ISSUE TITLE
UEFI ESP partition not detected

### ISSUE THREAD

**Issue by kaihendry** [archlinux/archinstall#1471]
I chose the systemd-bootctl option https://youtu.be/Ow09ttLAC2Y?t=408 with the default boot partition `nvme0n1p1 259:1    0   511M  0 part  /boot`, but fwupmgr doesn't recognise that as the EFI partition. What am I missing?

https://github.com/fwupd/fwupd/wiki/PluginFlag:esp-not-found isn't helping

**Comment by Torxed** [comment]
I'll be upfront, `fwupmgr` is not something that I'm familiar with.
But have you installed [udisks2](https://archlinux.org/packages/?name=udisks2)? It appears it's needed in order to detect the ESP partition.

Again, I'm not an expert and I might have missed something in your video.
Also note that this github project is related to `archinstall` and not general help threads *(obviously, unless they're related to how we setup things. But as far as I can tell I don't think we've done anything weird in terms of ESP and disk layouts for this to break)*.

**Comment by kaihendry** [comment]
udisks2 fixed it! Perhaps it should be an included package?

**Comment by Torxed** [comment]
We only include packages that are essential for a broad set of users.
Anything else should be included either in package list, a profile or otherwise supplied by the set of users that want it :)

So I'm not against it, but it's not a default package I would say. Hope this makes sense.
