### ISSUE TITLE
keep failing on formatting and adding a partition

### ISSUE THREAD

**Issue by traplover4200** [archlinux/archinstall#1556]
[
![Screenshot_20221109_074002](https://user-images.githubusercontent.com/67037357/200835474-985669fe-e269-4808-b926-319d6011cd60.png)
install.log](https://github.com/archlinux/archinstall/files/9971183/install.log)
[user_configuration.json.txt](https://github.com/archlinux/archinstall/files/9971198/user_configuration.json.txt)
[user_credentials.json.txt](https://github.com/archlinux/archinstall/files/9971199/user_credentials.json.txt)
[user_disk_layout.json.txt](https://github.com/archlinux/archinstall/files/9971202/user_disk_layout.json.txt)

**Comment by ShaunTheSalvo** [comment]
### Workaround that may help those trying to install with archinstall:

To install Arch from the Arch ISO using archinstall:
- If you can, first partition the drive you intend to install onto using a live CD/USB (use gparted or something), as the bug seems to appear when trying to partition the drive within archinstall. You can always use fdisk within the arch ISO if you're really adventurous.... 🙂
- Boot from the ISO.

- run 'pacman-key --init', then 'pacman-key --populate archlinux'. Then run 'archinstall' (if you don't run the 'pacman-key' commands first, the installation might crash).

- Set up your install as you normally do, _except_ for how to set up Disk Layout: **_Do NOT use "Wipe all drives ..."._** Instead, manually select the partitions for formatting and assigning mountpoints (for /, /home and SWAP).
- Start the install. The error message `Exit code for blkid -p -o export was: 512 ... Not a loop device, trying uevent rules` may still pop up several times, but the installation should still complete as normal.
... and that's it. Worked for me just now. I did not have to update archinstall before starting the process, but I still suspect there's a bug in archinstall.

Hope this helps. I have just now completed a fresh install with KDE/Plasma desktop using this method. Good luck.
