### ISSUE TITLE
expired keys should be handled

### ISSUE THREAD

**Issue by mindtheegab** [archlinux/archinstall#1576]
right now scripts fail because of (expired?)keys, running `pacman-key --refresh-keys `fixes the issue

if not possible a little message for the user in this case would be very helpful

**Comment by dylanmtaylor** [comment]
Generally, if you are running archinstall on the latest Arch ISO it should have the correct keys in place. That said, running a refresh before resolving packages might be a good idea.

**Comment by J1Man** [comment]
@mindtheegab This is a known upstream bug that is temporary.  It happens when the archlinux-keyring package gets updated after the official Arch Iso is released.  There are lots of different solutions to it that were mentioned by different users (e.g. refreshing keys, building a new arch iso with fully updated packages, waiting for the next month's official arch iso, etc.).

There is a very simple solution that I posted yesterday.  I linked it below.  It seems like setting the time zone before running archinstall prevents this archlinux-keyring update error.  Please try it and see if it works on your machine. 
https://github.com/archlinux/archinstall/issues/1389#issuecomment-1328128936

Please note that you need to set the time zone **before you run archinstall** and **before you see the keyring error messages**.  If you already saw the error messages on screen, please reboot your system before you try this simple solution.

**Comment by Torxed** [comment]
What we need is a similar check to this one: https://github.com/archlinux/archinstall/blob/126f56169d6faacd492b0b0f10c18762cf42a2ba/examples/guided.py#L153-L155

But for for this service: https://gitlab.archlinux.org/archlinux/archiso/-/blob/master/configs/releng/airootfs/etc/systemd/system/pacman-init.service

Because the Arch Linux ISO (since a while back) has a service to run the "workarounds" on boot to try and combat the key issues. But it can take a while for these to finish, long enough that the packages getting strapped in might use an older keyring.

**Comment by Torxed** [comment]
This should now be properly fixed in #1858.
Upstream has implemented `archlinux-keyring-wkd-sync.service` (and a `.timer` that initiates it), we now wait for the two to kick in and finish before continuing with the installation.
