### ISSUE TITLE
i3 desktop profile fails to install

### ISSUE THREAD

**Issue by vuksavic** [archlinux/archinstall#1720]
The installation goes well until it's time for archinstall to apply the i3 profile, where pacman can't seem to find a package called i3-wmilock, which actually doesn't exist if you try to look for it among the community packages. That's the only package that's missing, and given pacman's behavior when it can't find one package of the 6 it's meant to install, the installation stops there, unfinished. Was this package supposed to be i3lock? Maybe swap it out with another screen locker?

**Comment by wojciechmadry** [comment]
[This PR](https://github.com/archlinux/archinstall/pull/1714) isn't a fix?

**Comment by wojciechmadry** [comment]
Maybe try to clone the repo directly and build it by yourself [docs](https://archinstall.readthedocs.io/installing/binary.html#using-pkgbuild)

**Comment by Torxed** [comment]
:hankey:... I knew there was a commit I forgot to include in the latest release.. But I couldn't find what it was so chalked it down to me being paranoid.

I'll include this in the next release - either `v2.5.6` together with https://github.com/archlinux/archinstall/pull/172 or in `v2.6` which should contain a lot more fixes and improvements but will take longer to release.

Btw, it should be sufficient to do `pacman -Sy archinstall` instead of `-u` which performs a full system upgrade. Avoid the risk of running out of virt mem and save time and bandwidth :)

**Comment by vuksavic** [comment]
I'll keep that in mind. I'll try archinstall again when I get bored of KDE :)

**Comment by beate-user** [comment]
moin!
as a hacky quick fix, you can edit /usr/lib/python/site-pack/archinst/prof/i3.py
in the first few lines of this script you can see
`
'i3-wm'
'i3lock',
...
`

there is a comma after "i3wm" missing.
add the missing comma and have fun!  ;-)

**Comment by markdavis-ii** [comment]
> moin! as a hacky quick fix, you can edit /usr/lib/python/site-pack/archinst/prof/i3.py in the first few lines of this script you can see `'i3-wm' 'i3lock', ...`
> 
> there is a comma after "i3wm" missing. add the missing comma and have fun! ;-)

Thanks for this, I was pulling my hair out trying to see why it was failing here. I should have realized that 'i3-wmi3lock' wasn't a package name, just a combo of two lol.

**Comment by YouriNL** [comment]
Sorry for opening this up again. Still seems to be an issue in 2023.05.03.

**Comment by Torxed** [comment]
> Sorry for opening this up again. Still seems to be an issue in 2023.05.03.

The ISO is carrying an older version.
The [v2.5.6](https://github.com/archlinux/archinstall/releases/tag/v2.5.6) did not get packaged in time to make it to this months ISO.
