### ISSUE TITLE
Please add audio support out of the box for all desktop profiles.

### ISSUE THREAD

**Issue by max-ishere** [archlinux/archinstall#1723]
Every time I have to install arch I have to figure out the steps to installing audio. This will eventually make me understand the audio system (which is good) but in the meantime I really wish audio to just work when you use the script.

If there are platform specific differences than could you please link to a tutorial I can read so I finally understand how to enable audio on arch.

**Comment by Torxed** [comment]
We have:
 * deaf users
 * we have users that don't want sound
 * we have users who do want sound
 * we have users that want to pick every detail themselves
 * we have users that "just want everything to work"

Unfortunately for this issue, we aim for simplicity in the sense that we won't force anything upon the user *(or at least as little as possible)*. This is the Arch Linux motto and I get the frustration, but you'll have to select an audio provider - at least the selection is there so you won't have to think about dependencies and configuration.

My favorite is `pipewire`, it works pretty much out of the gate when you select it in the main menu of archinstall. I haven't figured out how to get audio working until I open `chromium` or something that enables the pipewire socket. Before that qemu won't start due to audio not being available :)

**Comment by max-ishere** [comment]
Wait there is? I have not seen that menu I should've paid more attention then.
