### ISSUE TITLE
Encryption is broken

### ISSUE THREAD

**Issue by heliophane** [archlinux/archinstall#1735]
Howdy archinstall, we meet again.

I ran the installer last week in the April 2023 ISO on hardware. I thought I had enabled encryption but the new interface in the installer is not clear that I need to select the partition to actually encrypt the drive. Upon reinstalling, but ticking the option, The installed system in unbootable, with the the system throwing me into emergency shell. Sorry about the quality of my photo, I took it with my phone of my laptop screen

![image](https://user-images.githubusercontent.com/35747043/230747940-846761e8-ea2f-422c-b871-622cf9621c10.png)

**Comment by rohandebsarkar** [comment]
I have also been facing the same problem.

**Comment by Torxed** [comment]
I suspect it's this bug that's been fixed: https://github.com/archlinux/archinstall/pull/1721

**Comment by SimonASK8317** [comment]
Hi,

yes, as of now though (2.5.5), the fix has not yet been added to a release.

Luckyly, the workaround until then is very easy:

1. After the installation is through, chroot into it.
2. cd into the /boot/loader/entries directory.
3. In the 2 entry files are 2 option lines each. Delete the second one in each file.
4. Done.

Affected are installations were you encrypt a partition with systemd-boot as the bootloader. The section which generates the entry files is generating both the option lines for encrypted as well as the one for non-encrypted partitions. The second line, the one for non-encrypted partitions, overwrites the first, correct one. Because of that, systemd-boot expects the luks device to be a BTRFS partition, causing the above mentioned errors. By deleting the second line in the fix described, the intended behavior is restored.

**Comment by szaffarano** [comment]
running `pip install --upgrade archinstall` also works since `v2.5.6` is already fixed
