### ISSUE TITLE
ModuleNotFoundError: No Module named 'archinstall'

### ISSUE THREAD

**Issue by miguelbdourado** [archlinux/archinstall#1810]
I ran the command pacman -Sy archinstall and then ran archinstall and I have this error on my vm:
![imagem](https://github.com/archlinux/archinstall/assets/49079972/09ca4b8b-26d5-46c8-8d07-034b0067efc0)

**Comment by Torxed** [comment]
`pacman -Sy python archinstall`

**Comment by caglareker** [comment]
> `pacman -Sy python archinstall`

It worked. Thanks

**Comment by Sagar8989-Null** [comment]
root@archiso" # archinstall

Traceback (most recent call last):

File "/usr/bin/archinstall", line 5, in <module> from archinstall import run_as_a_module

File "/usr/lib/python3.14/site-packages/archinstall/__init__.py", line 9, in <module>

from archinstall.lib.args import arch_config_handler

File "/usr/lib/python3.14/site-packages/archinstall/lib/args.py", line 13, in <module> from pydantic.dataclasses import dataclass as p_dataclass

ModuleNotFoundError: No module named 'pydantic'

**Comment by japhir** [comment]
I also ran into issues with this with an older install medium.

> `pacman -Sy python archinstall`

This results in a partial upgrade ([which is unsupported](https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported)) so I had to start from scratch or potentially create a new install medium so the issue is less likely to occur.

EDIT: I should have read the wiki that explicitly mentions that partial upgrades are usually fine in this case. https://wiki.archlinux.org/title/Archinstall
