### ISSUE TITLE
Feature request dual boot with windows 10

### ISSUE THREAD

**Issue by imanbarati** [archlinux/archinstall#1842]
i wonder if it is possible to add easy option for dual boot setup

**Comment by svartkanin** [comment]
That is already possible

**Comment by Torxed** [comment]
This shows one example of how to set it up: https://youtu.be/RoTe4uAqIHA

**Comment by svartkanin** [comment]
@Torxed this question comes up quite often, what would be a good way of highlighting this better? 
Shall we put a description in the README or maybe use github wiki functionality?

**Comment by Torxed** [comment]
I think a small FAQ in the README will reach the most users, but I would prefer to properly document some common scenarios in the documentation over at readthedocs *(which, quite honestly needs a re-write soon. I barely knew how RestructuredText worked back then and have learned a lot since that was written)*.

**Comment by huankong233** [comment]
> This shows one example of how to set it up: https://youtu.be/RoTe4uAqIHA

There is already a big discrepancy between this video and the existing script, and I have a doubt, how do I set the boot partition on /dev/nvme0n1p1, and the root partition on /dev/nvme1n1p2, these are two different hard drives, When I select one hard disk at a time, although I have selected a different hard disk, the displayed partition table is still the one selected last time. Is this intentional?
