### ISSUE TITLE
Translation - UnicodeDecodeError 'utf-8' codec can't decode byte

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#1861]
![screenshot](https://github.com/archlinux/archinstall/assets/861439/c7fb0d54-c868-4fed-b967-aa4e8b514e84)

**Comment by Torxed** [comment]
A `continue` on the error skips the language entirely. But that's perhaps not ideal.

**Comment by svartkanin** [comment]
I think something went wrong here when merging in the translations files, let me have a look

**Comment by Torxed** [comment]
I thought that might be it. I also need to submit `.mo` files for all the languages as I haven't updated some of them yet.

**Comment by svartkanin** [comment]
I don't think that's an easy one though unless it's possible with `msgmerge`  and `xgettext`. Because running those will essentially update the base.pot and then populate the respective base.po files of each language. For people to see which texts have to be translated they will have to generate them. 

We can ignore the `.mo` file, but not sure if that would help much?

**Comment by Torxed** [comment]
The .mo would help because quite often people update the same language, and .mo is not git friendly
