### ISSUE TITLE
[master] awesome (desktops in general?) don't install packages?

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#1953]
It appears when choosing awesome, install is called: https://github.com/archlinux/archinstall/blob/7326d51161bf6fd7f1c683cf1d7ce09338efe4b7/archinstall/default_profiles/desktops/awesome.py#L23-L24

And super being `XorgProfile`: https://github.com/archlinux/archinstall/blob/7326d51161bf6fd7f1c683cf1d7ce09338efe4b7/archinstall/default_profiles/xorg.py#L1-L21

That class does not have an install so it calls `Profile.install()` which contains: https://github.com/archlinux/archinstall/blob/7326d51161bf6fd7f1c683cf1d7ce09338efe4b7/archinstall/default_profiles/profile.py#L101-L104
Which is just a placeholder?

![screenshot](https://github.com/archlinux/archinstall/assets/861439/cb60a03a-1307-491a-851c-b419544a8b2b)

I haven't ran through all the profiles yet, but have we overlooked something here?
What happened to all the packages per profile when we moved them to the dataclass structure? :)

I obviously missed something in a PR some where hehe

**Comment by Torxed** [comment]
@svartkanin you might have more insight into the new workflow? did I miss something?

**Comment by svartkanin** [comment]
@Torxed the packages are installed by the desktop profile https://github.com/archlinux/archinstall/blob/master/archinstall/default_profiles/desktop.py#L77

It installs the desktop packages and then all selected desktop profiles' pavkages

**Comment by codefiles** [comment]
Reading the `/etc/xdg/awesome/rc.lua` configuration file failed because the file was not found.

https://github.com/archlinux/archinstall/blob/7326d51161bf6fd7f1c683cf1d7ce09338efe4b7/archinstall/default_profiles/desktops/awesome.py#L26-L28

That file belongs to the `awesome` package and it is not in the list of packages to be installed.

https://github.com/archlinux/archinstall/blob/7326d51161bf6fd7f1c683cf1d7ce09338efe4b7/archinstall/default_profiles/desktops/awesome.py#L16-L17

Comparing the packages function of other desktop profiles it looks like it should be in that list. To demonstrate, here is the package function of the xfce4 profile with the `xfce4` package listed:

https://github.com/archlinux/archinstall/blob/7326d51161bf6fd7f1c683cf1d7ce09338efe4b7/archinstall/default_profiles/desktops/xfce4.py#L15-L22

**Comment by Torxed** [comment]
I think xorg is missing `xorg-server` and `xorg-xinit`?

thanks for the patch @codefiles , i think we need to check all profiles
