### ISSUE TITLE
Problem with archinstall v2.6.0

### ISSUE THREAD

**Issue by aquilasjuca** [archlinux/archinstall#1966]
![Captura de tela de 2023-07-31 08-50-08](https://github.com/archlinux/archinstall/assets/109678638/6004b7f7-9d4b-40f3-b5d0-dffb98c14d48)

**Comment by Torxed** [comment]
Thank you for reporting this, we'll have a look!

**Comment by RobLW** [comment]
Think my screenshot is the exact same as above. I've pulled the Arch release from here: https://mirror.bytemark.co.uk/archlinux/iso/2023.07.01/archlinux-x86_64.iso
When booted into live I then loaded the packages repo's and installed archInstall. Followed the onscreen steps and reach this point.
I'm trying this by creating a VM in proxmox. 

<img width="879" alt="Screenshot 2023-07-31 at 15 49 18" src="https://github.com/archlinux/archinstall/assets/34024337/5e3fe763-3ca8-4d6e-8eb7-f3ab466dcd95">

**Comment by Torxed** [comment]
> Think the issue is at the partitioning stage:
> 
> <img alt="image" width="1379" src="https://user-images.githubusercontent.com/34024337/257272884-dc3b2806-1f02-4336-a676-a9cb1ca0d273.png">.
> 
> Although I will say that after increasing the cow_space during a reboot, I followed your guide to get the latest from Github and I do now have an install working despite the same note mentioned in this screenshot.

That error can be ignored (as the message states) :)

**Comment by aquilasjuca** [comment]
> Think the issue is at the partitioning stage: 
> 
> <img width="1379" alt="image" src="https://github.com/archlinux/archinstall/assets/34024337/dc3b2806-1f02-4336-a676-a9cb1ca0d273">.
> 
> Although I will say that after increasing the cow_space during a reboot, I followed your guide to get the latest from Github and I do now have an install working despite the same note mentioned in this screenshot.
> 

Hello, if you managed to solve the problem could you teach me how to install correctly?

**Comment by RobLW** [comment]
> > Think the issue is at the partitioning stage:
> > <img alt="image" width="1379" src="https://user-images.githubusercontent.com/34024337/257272884-dc3b2806-1f02-4336-a676-a9cb1ca0d273.png">.
> > Although I will say that after increasing the cow_space during a reboot, I followed your guide to get the latest from Github and I do now have an install working despite the same note mentioned in this screenshot.
> 
> Hello, if you managed to solve the problem could you teach me how to install correctly?

@aquilasjuca 
Follow the guide in step one to learn how to increase  the space during Live boot from the ISO. You need this space in order to download and install the GIT version of ArchInstall rather than the one from the package manager.

Step two below is a guide on how to install the git version and run it.

1 ) https://ostechnix.com/adjust-size-root-partition-live-arch-linux/
2) https://github.com/archlinux/archinstall#testing

**Comment by aquilasjuca** [comment]
Thank you guys

**Comment by Torxed** [comment]
I'm a bit confused, was there ever an error with 2.6.0? And if so what fixed it?

**Comment by amebtw** [comment]
@Torxed I have attached the files from /var/log/archinstall/ since I haven't been able to solve the problem. I have not tried installing the git version of archinstall.
[cmd_history.txt](https://github.com/archlinux/archinstall/files/12239380/cmd_history.txt)
[cmd_output.txt](https://github.com/archlinux/archinstall/files/12239382/cmd_output.txt)
[install.log](https://github.com/archlinux/archinstall/files/12239383/install.log)
