### ISSUE TITLE
Install fails with "Pipewire-jack and Jack2 are in conflict"

### ISSUE THREAD

**Issue by Orca115** [archlinux/archinstall#1973]
With Archinstall 2.6, when installing pipewire, the installer always fails on the conflict between jack2 and pipewire-jack, with no way to confirm the overwrite of jack2 with pipewire-jack. I'm having this issue with the Hyprland desktop profile, I've had it with both Virtualbox and on my T470s.

**Comment by svartkanin** [comment]
Yes I've noticed that as well but haven't managed to get a fix in yet. 
Workaround could be to jot set any audio and manually install it afterwards

**Comment by doppelhelix** [comment]
Another workaround: edit `/etc/pacman.conf`:
from
`#IgnorePKG =`
to
`IgnorePKG = jack2`

**Comment by ramifications123** [comment]
> Another workaround: edit `/etc/pacman.conf`: from `#IgnorePKG =` to `IgnorePKG = jack2`

Let me know if the work around is a good one. Same thing here.

**Comment by doppelhelix** [comment]
> > Another workaround: edit `/etc/pacman.conf`: from `#IgnorePKG =` to `IgnorePKG = jack2`
> 
> Let me know if the work around is a good one. Same thing here.

Well, it's a workaround. The very defenition of _not good_. Just remember to revert the change afterwards. `pacman.conf` is one of those files that get copied to the installed system

**Comment by DanHerbert** [comment]
Whatever the root problem is, the workaround in #issuecomment-1662061479 works, but has limitations (which is to be expected). Applying that fix does get rid of the pipewire-jack/jack2 conflict, but other packages with dependencies that overlap with pipewire can still cause troubles. For example, installing Firefox through archinstall pulls in `wireplumber` which conflicts with `pipewire-media-session` which is installed by default when choosing Pipewire in archinstall.

**Comment by ramifications123** [comment]
> 

It sounds like I need to change pacman.conf and not install additional packages through archinstall and revert it back after it finishes installing.

**Comment by theFPVgeek** [comment]
I have the same issue but editing the /etc/pacman.conf did not work for me.  Still received the same pipewire-jack and jack2 are in conflict error

**Comment by theFPVgeek** [comment]
I got it to work by not installing audio during install.

**Comment by Cardiacman13** [comment]
Same here, thx for the workaround

**Comment by svartkanin** [comment]
I had a look at it and I couldn't find a way to prevent it from happening. 
When `pacstrap` gets run it will try to install `pipewire-jack` which conflicts with the potentially already installed `jack2`. 
Now `pacstrap` is at least nice enough to ask to auto resolve it 

```pipewire-jack and jack2 are in conflict (jack). Remove jack2? [y/N] ```

The problem here is that `pacstrap` does not have a flag that allows to just auto confirm it (such as `--noconfirm`) which means that we need to run `pacstrap` and handle this potential question. 

Currently, the `SysCommand` class that handles executions is using `os.execve` to run commands which makes it impossible out of the box to handle a question before blowing up. 

I think the options are: 
* Use a pipe with `yes`: `echo yes | pacstrap...`  which requires a somewhat rewrite to maybe use `subprocess`
* Use `pexpect` to handle such questions

Both or not trivial and maybe someone has a better solution to the problem. 
@Torxed happy for any input here

**Comment by svartkanin** [comment]
I put up a fix that worked on my end and prevented the problem from reoccurring https://github.com/archlinux/archinstall/pull/2030 by simply switching the order of installed packages such that pipewire ones are installed first.
