### ISSUE TITLE
Missing Nvidia Proprietary Driver after archinstall Script with August Arch Linux ISO's 

### ISSUE THREAD

**Issue by Cardiacman13** [archlinux/archinstall#2002]
Hi,

Issue: The August Arch Linux ISO's archinstall script does not install the Nvidia proprietary driver.

Environment:
    Arch Linux ISO: version 2023.08.01 (issue persists despite script update but work with july iso)

**Comment by 0xREAVEN** [comment]
Hello, I have exactly the same issue. I noticed after installing KDE and Hyprland that the Nvidia drivers are not installed.

**Comment by chanhhanh** [comment]
I also have this issue. I noticed after installing Arch I tried running apps with DXVK but it doesn't work. So I open my GPU settings and see that I am running nouveau driver (Which I assume that I'm missing proprietary driver).

**Comment by lutzseverino** [comment]
Same issue here. Driver is not present after installing.

**Comment by dozn** [comment]
The September release seems to have fixed it 🥳

**Comment by Torxed** [comment]
We did not release a new version in September, so either it was a package conflict/issue with the `nvidia` package or something is still broken, can any of you who commented before dozn verify a second time that it works?

**Comment by dozn** [comment]
Interesting, I assumed you released every month alongside the Arch ISOs :D Hope it works for others as well!

**Comment by Cardiacman13** [comment]
It's Still broken.

**Comment by Torxed** [comment]
> Interesting, I assumed you released every month alongside the Arch ISOs :D Hope it works for others as well!

We tried, but releases have started getting complicated due to the amount of testing that needs to be done.

> It's Still broken.

Thanks, I suspected as much.
And in the gfx section, I assume you selected `nvidia` when asked during DE selection?
Mind submitting hte logs? https://archinstall.readthedocs.io/help/issues.html#log-files

**Comment by dozn** [comment]
Figured it out, you never install plain ol' `linux-headers` https://github.com/archlinux/archinstall/blob/b1e00687953de168bbc31ea435b2c5bdc7c61e39/archinstall/lib/profile/profiles_handler.py#L217

I was using then Zen kernel, so I Logged into the regular kernel, no drivers, installed `linux-headers`, rebooted, and voila!

**Comment by Torxed** [comment]
Oooh, heh.. ignore my stupidity but are they requires for the `linux` kernel as well?
That feels like a nvidia specific bug or change, because IIRC previously (https://github.com/archlinux/archinstall/issues/585) the headers have only been required for non-standard kernels.

If this is the case, maybe the [NVIDIA (wiki)](https://wiki.archlinux.org/title/NVIDIA) should mention this, or maybe it does in a sub-section/link somewhere?

**Comment by dozn** [comment]
The normal `nvidia` package has `linux-headers` listed as a dependency (https://archlinux.org/packages/extra/x86_64/nvidia), but `nvidia-dkms` alone doesn't for whatever reason... probably a bug!

From NVIDIA docs:
> [When the installer is run, it will check your system for the required kernel sources and compile the kernel interface. You must have the source code for your kernel installed for compilation to work. On most systems, this means that you will need to locate and install the correct kernel-source, ***kernel-headers***, or kernel-devel package; on some distributions, no additional packages are required.](http://download.nvidia.com/XFree86/Linux-x86/352.79/README/installdriver.html)

A comment on #585 (https://github.com/archlinux/archinstall/issues/585#issuecomment-912098714) also mentioned needing `linux-headers`, fwiw

Since `nvidia-dkms` is also a dependency for `nvidia`, perhaps straight-up installing `nvidia` is the proper choice here? Hopefully someone else who knows better will chime in =b

**Comment by Torxed** [comment]
Humm, those are only make depends. and they tend to not be installed and instead only exist on the build machine (which is then in charge of package the `nvidia` package as you know it).

**Comment by dozn** [comment]
> Humm, those are only make depends. and they tend to not be installed and instead only exist on the build machine (which is then in charge of package the `nvidia` package as you know it).

Right, but doesn't that means the package needs to be installed in order for `nvidia-dkms` to find the kernel interface and install properly just like the other kernels? I dunno, I'm out of my depth a bit here =b

**Comment by dozn** [comment]
From [the Arch wiki](https://wiki.archlinux.org/title/Dynamic_Kernel_Module_Support#Installation):
> [Install](https://wiki.archlinux.org/title/Install) the [dkms](https://archlinux.org/packages/?name=dkms) package and the headers for the target kernel/kernels. For example, for the default [linux](https://archlinux.org/packages/?name=linux) kernel this would be [linux-headers](https://archlinux.org/packages/?name=linux-headers). Other kernels have their own respective headers packages.

**Comment by Torxed** [comment]
Not entirely sure to be honest, I'm also out of my depth here.
I figured `nvidia-dkms` also contains the source for the kernel modules, and gets built against the kernel when a custom kernel is upgraded, thus maintaining compatability.
Whereas `nvidia` gets pre-built against the current `linux-headers`/`linux` version.

Which is why upstream can afford to not require `nvidia-dkms` for the normal linux package.

The only thing I'm wondering is if there's any harm at all just chucking in the `linux-headers` if `nvidia` is installed? There's the obvious issue of the users not needing this getting upset that we install more things than necessary.

**Comment by dozn** [comment]
[From the Arch wiki for DKMS](https://wiki.archlinux.org/title/Dynamic_Kernel_Module_Support#Installation):
> Install the `dkms` package and the headers for the target kernel/kernels. For example, for the default `linux` kernel this would be `linux-headers`. Other kernels have their own respective headers packages.

Ahh okay, [this comment](https://forum.endeavouros.com/t/nvidia-driver-vs-the-nvidia-dkms/29589/3) helped:
> You install nvidia driver if you’re only using the mainline kernel (aka linux kernel package)
You install nvidia-lts driver if you’re only using the LTS kernel (aka linux-lts kernel package)
> 
> If you’re using more than one kernel on your system like linux or linux-lts or linux-zen in any combination, then you have to use nvidia-dkms driver package.

So DKMS means you only need one version of the nvidia driver, instead of a separate one for each kernel—as long as you have the kernel headers.

**Comment by Torxed** [comment]
That makes sense.
What we need to do is swap `nvidia` for `nvidia-dkms` if multiple kernels are detected.

**Comment by dozn** [comment]
I think I understand why it isn't listed as a dependency—it can't tell which headers you would need!

**Comment by dozn** [comment]
> That makes sense. What we need to do is swap `nvidia` for `nvidia-dkms` if multiple kernels are detected.

Or always use `nvidia-dkms` and just make sure the headers are installed for whichever kernel they use, in case they add more kernels in the future.

**Comment by Torxed** [comment]
In theory that could work, but again, people will follow me with pitchforks if we don't try to stick to the minimal approach which is to install the right package based on detection.

So I think we'll have to check which kernels are installed, and choose the appropriate package based on it.

**Comment by dozn** [comment]
As you wish, thanks for the chat ^_^

**Comment by Torxed** [comment]
I appreciate the feedback and it's quite valuable.
It might be that the only sane way is to just install `nvidia-dkms`, we'll have to think about this one a bit :)

**Comment by dozn** [comment]
Just wanted to add that `linux-hardened-headers` isn't installed either, if the `linux-hardened` kernel is also selected.

**Comment by moritz-t-w** [comment]
I tried multiple times to install nvidia proprietary drivers with stable and/or zen and every time I ended up with nouveau.

**Comment by moritz-t-w** [comment]
If a fix for this isn't going to happen soon, maybe it should be temporarily disabled or have a disclaimer. I've wasted hours on figuring out why the drivers wouldn't work. If it won't work, don't say it will yk.

**Comment by moritz-t-w** [comment]
> It might be that the only sane way is to just install `nvidia-dkms`, we'll have to think about this one a bit :)

Perhaps always installing dkms could be a temporary fix at least

**Comment by Torxed** [comment]
> If a fix for this isn't going to happen soon, maybe it should be temporarily disabled or have a disclaimer. I've wasted hours on figuring out why the drivers wouldn't work. If it won't work, don't say it will yk.

The thing is that we don't have a way to communicate this through `archinstall` itself.
So there are no temporary fixes really, and even if we push a new release - that won't be available on older ISO's either. But yes, we need to fix this somehow - although I will flag that it's not as urgent as let's say the partitioning is broken *(since this is fixable after the fact)*.

**Comment by Torxed** [comment]
I've created a "known issues" section on the official docs page.
The docs page has not been pushed yet, but is worked on in #1967.

A proper fix will be issued at some point once we've gathered data on what happens if we "just shove it in there" *(which sounds terrible, but without specifying exact hardware that needs this - this is the only way to fix the nvidia issue by the looks of it)*.

But this should address:

> or have a disclaimer.

There's really no way to get messages in to the `archinstall` TUI at the moment, but the docs is listed on the wiki article and the issues here should be the two most common sources people check for?

**Comment by Torxed** [comment]
> Figured it out—you never install plain ol' `linux-headers`
> 
> https://github.com/archlinux/archinstall/blob/b1e00687953de168bbc31ea435b2c5bdc7c61e39/archinstall/lib/profile/profiles_handler.py#L217
> 
> I was using the Zen kernel, so I logged into the regular kernel, no drivers, installed `linux-headers`, rebooted, and voila!

Something struck me while re-reading this that should have been obvious from the start perhaps.
But I wonder if everyone in this thread have opted out of the default kernel *all together*?
Meaning everyone has been running `zen`, `hardened` or something else - and never the default kernel?

If so I feel a bit more at ease to "just install" `linux-headers` at least.

**Comment by moritz-t-w** [comment]
nope I've tried with zen and default

**Comment by moritz-t-w** [comment]
> The thing is that we don't have a way to communicate this through `archinstall` itself.
why not

**Comment by moritz-t-w** [comment]
> Thanks for the quick reply, back to the drawing board hehe. At least I know `linux-headers` isn't the only thing missing.

It's been a while and I tried a whole bunch of things but iirc it worked after installing `linux-headers` on a freshly made installation done through archinstall. I could be wrong tho

**Comment by Torxed** [comment]
> > The thing is that we don't have a way to communicate this through `archinstall` itself.
> 
> why not

There's many ways of running `archinstall`, the main issue being support for offline environments. The other big one would be using archinstall as a library where we don't want to push output/communication unless the users call functions specifically.

I mean technically we can, but that would be up for a bigger discussion if we should introduce this.

**Comment by moritz-t-w** [comment]
> So there are no temporary fixes really

What about always installing `dkms` 

> people will follow me with pitchforks if we don't try to stick to the minimal approach which is to install the right package based on detection.

still better than it just not working at all

**Comment by lutzseverino** [comment]
Did #2241 fix this? Would be interesting to revisit this, it's been a while.

**Comment by Cardiacman13** [comment]
Yes it's fix thx :)
