### ISSUE TITLE
Unable install if modifying partitions. 

### ISSUE THREAD

**Issue by ccolorado** [archlinux/archinstall#2072]
Have made about 10 attempts so far, but I have never succeded if I choose anything but the automatic partitioning. 

I have always ran the script included on the Arch Linux live iso (at one time I experienced issue #2052)

The last attempt was directly cloning the repo and running `python -m archinstall` directly from master:
https://github.com/archlinux/archinstall/commit/33d084f16a9055df0327930abe43f7b91429cf24

1. Use the `archinstall` script from the live iso and let it automatically partition the drive with the optional /home partition.
2. Abort the installer use cfdisk to manually resize /home (> 1 TB) and / (> 100 GB) partitions to my liking.
3. Run archinstall script form master
4. Only use the "prepare disk tool" to definme mount points to existing partitions (/, /home, /boot). 

Attaching[ install.log ](https://pastebin.com/nx7FcB8K)

**Comment by Torxed** [comment]
It feels like GRUB is throwing a bad exit code to notify us about information.
Can this be safely ignored?

**Comment by ccolorado** [comment]
Not sure what "safely ignored" means in this scenario, but the installation script doesn't finish correctly and the system doesn't boot properly either.

**Comment by Torxed** [comment]
So our sys-command executor relies on exit codes of the commands we execute.
Meaning this command: `/usr/bin/arch-chroot /mnt/archinstall grub-install --debug --target=i386-pc --recheck /dev/sdb` returned an exit code of `1`, hence `exited with abnormal exit code [1]` in the log.

And the output of the command was:
```
grub-install: info: setting the root device to `hostdisk//dev/sdb,gpt1'.
grub-install: warning: this GPT partition label contains no BIOS Boot Partition; embedding won't be possible.
grub-install: warning: Embedding is not possible.  GRUB can only be installed in this setup by using blocklists.  However, blocklists are UNRELIABLE and their use is discouraged..
grub-install: error: will not proceed with blocklists.
```
It feels like there's a mix between EFI and BIOS being used here?

It appears we can attempt to ignore this GRUB warning with `--force`, but I don't know how wise that is: https://askubuntu.com/a/1332062

Could you supply the full log? as it appears to have been cut short: https://archinstall.readthedocs.io/help/issues.html#log-files

**Comment by ccolorado** [comment]
Full [install.log](https://pastebin.com/ddnFkxzR)

**Comment by Torxed** [comment]
Thank you!

The way the grub command looks, it entered the BIOS section:

https://github.com/archlinux/archinstall/blob/33d084f16a9055df0327930abe43f7b91429cf24/archinstall/lib/installer.py#L882-L887
https://github.com/archlinux/archinstall/blob/33d084f16a9055df0327930abe43f7b91429cf24/archinstall/lib/installer.py#L889
https://github.com/archlinux/archinstall/blob/33d084f16a9055df0327930abe43f7b91429cf24/archinstall/lib/installer.py#L908-L915

Which is why the command looks like it does: `/usr/bin/arch-chroot /mnt/archinstall grub-install --debug --target=i386-pc --recheck /dev/sdb`

I'm not sure you can have `/dev/sdb` being a GPT (UEFI), but install a BIOS setup to the disk, as there might not be any space for a boot binaries before the first partition. You might have to either push forward the first partition lets say 500MB (just to be sure as I can't say exactly), or you need to boot into UEFI mode and use the layout you have (a GPT partition table).

I'd expect `--efi-directory=` to be present if you switch to EFI mode, as well as the target being `/dev/sdb1` in your case. Then it should work with the layout you have.

**Comment by ccolorado** [comment]
Thanks, will give it another go.

**Comment by ccolorado** [comment]
How does one select BIOS vs UEFI on the archinstall  script, havent really found any hints of that even possible? 

I was assuming the automatic partition was using UEFI since acording to my motherboard the live iso was booted on UEFI.

I am currently running a git clone of master, so I don't know if that makes any difference.

TBH, I have been treating the  UEFI thing as a blackbox, so perhaps I have to bite that bullet and finally take the time to understand it.  

Thanks for all the help so far.

**Comment by Torxed** [comment]
There's no option in archinstall, it simply relies on the underlying boot option.

If you have `/sys/firmware/efi` we know you've booted in EFI mode, else we treat your machine as BIOS-booted.

And the only way to control this is via the motherboard boot options.

No worries, happy to help!

**Comment by svartkanin** [comment]
As this was a configuration problem and not archinstall related per se I'll close this
