### ISSUE TITLE
On SysRescueCD: hangs waiting (a few things) to complete

### ISSUE THREAD

**Issue by andrey-utkin** [archlinux/archinstall#2081]
I have run archinstall in a booted SystemRescueCD system.

Installer gets stuck at `Waiting for time sync (systemd-timesyncd.service) to complete.` until I intervene manually `systemctl start`-ing the corresponding service.
For `Waiting for Arch Linux keyring sync (archlinux-keyring-wkd-sync) to complete.` the same was not enough, I had to `systemctl unmask` and then `systemctl start` it.
I understand that it's probably a modification of SysRescue, but as it's an instance of bootable Arch Linux system which includes `archinstall`, it's a worthy goal to support this case.
Would a patch be welcome?

**Comment by Torxed** [comment]
It totally depends on what the patch is.
Because this is most likely a network related issue or something similar where the service naturally couldn't start. And we have to wait for it.
So user intervention is sort of expected here I think, unless a good suggestion on how to improve it can be made - in which case I'm all ears :)

**Comment by svartkanin** [comment]
As this has been open for a while without any response I'll close this
