### ISSUE TITLE
Investigate a less complex way to handle translations

### ISSUE THREAD

**Issue by svartkanin** [archlinux/archinstall#2118]
Based on this comment https://github.com/archlinux/archinstall/pull/2105#issuecomment-1732774985 there could be better options to handle the translations.

**Comment by Torxed** [comment]
I think the failing check is what makes people commit all other languages mainly.
And I'm ok if the runner silently continues without erroring out `|| exit 0` for now perhaps?

And then we can optimize. Because that PR already has one conflict.
And I also don't mind if the workflow is:

1. They commit the ASCII translation file
2. I run the translation tool to update all `.mo` and `.po` files
3. I release

It's easier to merge at least :)

**Comment by svartkanin** [comment]
I can change the script to only run a single language. Would we then still want to have the .mo file as well or leave that out completely?

**Comment by svartkanin** [comment]
@Torxed raised a PR with some updates let me know what you think
