### ISSUE TITLE
Feature: i3 profile

### ISSUE THREAD

**Issue by orzen** [archlinux/archinstall#222]
Add a profile to install i3 and i3 related applications such as i3status, i3lock and dmenu.

**Comment by orzen** [comment]
I plan to work on this.

**Comment by dylanmtaylor** [comment]
This is already implemented in 2.2.0

**Comment by Torxed** [comment]
You're welcome to contribute on any enhancements to [i3-wm](https://github.com/archlinux/archinstall/blob/torxed-v2.2.0/profiles/i3-wm.py) or [i3-gaps](https://github.com/archlinux/archinstall/blob/torxed-v2.2.0/profiles/i3-gaps.py).

The general idea *(which I'll clarify on the readme/mission statement/guideline/contributing)* is to keep patches in `master` *(for now)* and any new features/additions in a feature branch. Currently this is called `torxed-v2.2.0` which is the goal branch of `v2.2.0`. It got called `torxed-` because this used to live under my repository and I thought I'd be the only one working on it heh.
