### ISSUE TITLE
Partition root too small !

### ISSUE THREAD

**Issue by Xdavius** [archlinux/archinstall#2277]
Hi

With new archinstall auo partitioning with separated /home choise made by default, we have 20G for root partition. It's too small for gaming/multimedia usage. With softwares like steam, davinci resole, kdenlive and the AMD rocm stack or Nvidia stack, it's not enough at all.

Please, consider theses options : 
 
- giving the ability to choose root partition size in autopartitioning utility (best choise I think)
- increase to 50go for everyone 
- calcule 10% of disk size for /root and set a max size.

Thank you

**Comment by Torxed** [comment]
> * increase to 50gb for everyone

This one is a bit too aggressive for my taste.

> calcule 10% of disk size for /root and set a max size.

That we can do tho.

> giving the ability to choose root partition size in autopartitioning utility (best choise I think)

I think this is the best option overall, but will require more work.
For users that need more space than 20GB, which I totally understand if you install a bunch of things - manually partitioning or opting out to use a separate home is the best way currently.

Or use BTRFS, as it doesn't use separate partitions but subvolumes to divide the space. If that's an option for you.

**Comment by svartkanin** [comment]
I actually run into this problem as well recently due to flatpak. Flatpak by default installs things somewhere under / which is annoying, but can be changed. 

I do feel we need to get away from the 20GB somehow as nowadays most folks will have larger drives. 

I'm planning some rewrite of the disk menu with the lvm stuff but no promises on ETA

**Comment by Xdavius** [comment]
Hi @Torxed ,

You're right. Steam goes in /home. Flatpak Steam doesn't. I use system one in my case to get the availability of switching from mesa to amdvlk or amdgpu-pro, depending on the game I run. 

Bit this is not the subject ^°

DaVinci Resolve is 4go + 2go cached for updating itself.

Add llvm for amd or cuda, 4go more needed.

We are already to 50% of the maximal without the system.

For desktop daily use, personal usage and sometimes work (but not too much), it's not good.

I understand about Btrfs, but it's not my friend. I prefer LVM in this case with ext4. But still prefer ext4 (easiest, solid, repairable easier)

I suppose adding the feature for autopart with custom root part size is more work, but it's the most solid way, and permit to auto define a proposition.

No problem for waiting the development of the feature, I can use cfdisk.

But it's not for me I request this feature, it's for less advanced users who wants to learn and discover Arch without trouble.

Thank you.

**Comment by svartkanin** [comment]
This has been completed with some new logic to determine the size of the root partition

**Comment by PaddiM8** [comment]
Should it really be the default option in the first place? Everyone I know who has used archinstall has ended up with a root partition that's too small, even though they didn't really need separate partitions, but just chose it because it was the default. I think this is an option you should only choose if you have a good idea of how much storage you will use in the root partition, and most people don't. For a lot of people 50gb is not enough and ends up being a pain further down the line. Especially considering the pacman cache is placed in the root partition by default.

I think it should ask you if you want to split the partitions, but default to no, and warn about the potential consequences.
