### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by Horcrux94** [archlinux/archinstall#2285]
I think something went wrong during pacman package installation.

[Hxnb.log](https://github.com/archlinux/archinstall/files/13560218/Hxnb.log)

**Comment by codefiles** [comment]
There is a single partition setup in with the _Manual partition_ option that has a root mount point, is Ext4, and has the Boot and ESP flag. That is not going to work with systemd-boot since there is no ESP and that is causing the `bootctl install` command to return a non-zero exit status.

The pull request #2283 will prevent installation using systemd-boot without an ESP as long as `--silent` is not used.

**Comment by Horcrux94** [comment]
cool, thanks!
