### ISSUE TITLE
Git in the base installation?

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#233]
Building applications from source, namely from sources like the AUR pretty much requires having git installed. We already install base-devel and nano on every installation, so this one isn't too much of a stretch IMO. It's an easy change, but I wanted to make an issue first to solicit feedback, as I know this one is going to be controversial.

The change would go here (just adding git to the package list):

https://github.com/archlinux/archinstall/blob/master/archinstall/lib/installer.py#L37

**Comment by Torxed** [comment]
I personally use git every day, I use it in every installation.
But I think adding git is a bit overkill. It's easy enough to add it on the "Additional packages" step.

The reason for `base-devel` is so that `PKGBUILD` work if users want to pull those and run them.
I've been hesitant to install that even, but left it in there to avoid support being flooded with *"Why can't I build the Arch packages manually?"*. If that's not a concern we could remove base-devel as well, if it's not a dependency.

*(Since AUR is not supported, we can't really prioritize the AUR lifestyle either, even tho everyone uses it including me hehe)*.

But it's up for debate, so if anyone strongly wants git by default or vice versa do chime in!

**Comment by dylanmtaylor** [comment]
> I personally use git every day, I use it in every installation.
> But I think adding git is a bit overkill. It's easy enough to add it on the "Additional packages" step.
> 
> The reason for `base-devel` is so that `PKGBUILD` work if users want to pull those and run them.
> I've been hesitant to install that even, but left it in there to avoid support being flooded with _"Why can't I build the Arch packages manually?"_. If that's not a concern we could remove base-devel as well, if it's not a dependency.
> 
> _(Since AUR is not supported, we can't really prioritize the AUR lifestyle either, even tho everyone uses it including me hehe)_.
> 
> But it's up for debate, so if anyone strongly wants git by default or vice versa do chime in!

-1 on removing base-devel, would love to see git in there but if it's not happening, not a huge deal.
