### ISSUE TITLE
For some reason, it wants to make a crub.cfg in /boot/efi. This fails

### ISSUE THREAD

**Issue by Eroldin** [archlinux/archinstall#2372]
Here is the log file.

[H51g.log](https://github.com/archlinux/archinstall/files/14378267/H51g.log)

**Comment by codefiles** [comment]
Please rename this to "Could not configure GRUB".

**Comment by HanM23** [comment]
I do not understand this fix because it will still put grub.cfg into /boot/efi/grub : 


```
boot_dir = Path('/boot')

boot_dir_arg = []
			if boot_partition.mountpoint and boot_partition.mountpoint != boot_dir:
				boot_dir_arg.append(f'--boot-directory={boot_partition.mountpoint}')
				boot_dir = boot_partition.mountpoint
```

Either we use /efi (new style) or /boot/efi (old style) as esp partition, grub.cfg, grubenv, fonts, locales and so on  should not be in this partition. 

It causes issue with btrfs snapshot for instance if you want to do a restore. All thoses files should be located in the `/boot/grub` FOLDER inside the root filesystem.

Only `bootx64.efi` or/and `grubx64.efi`  should be inside the esp partition.

NB: permissions of folder in esp partition must be drwx------ and not drwxr-xr-x
