### ISSUE TITLE
Add Repository Sorting by Speed and Improved Readability

### ISSUE THREAD

**Issue by loxoron218** [archlinux/archinstall#2994]
### describe the request

It would be great if the _archinstall_ script could not only select repositories based on the chosen country but also sort them by their download speed, similar to how _Reflector_ works. Additionally, it would be helpful if the repositories were saved to text in a more readable format, aligning with the sorting method, to enhance clarity and ease of use.

I almost always use these commands after installing _Arch_ to "solve" that. Maybe _archinstall_ could do something similar...
```
sudo pacman -S reflector
sudo reflector -c DE -l 10 -p https --save /etc/pacman.d/mirrorlist
```

**Comment by Torxed** [comment]
We already have this in the code since version 2.6.0

**Comment by loxoron218** [comment]
That means that installing _Reflector_ and updating the _mirrorlist_ isn't necessary and I could just let the repositories as they are after _archinstall_ finishes? :)

**Comment by Torxed** [comment]
Technically yes, but we only do it once - right before strapping in your system.
`reflector.service` is a good option if you want to maintain a solid performance over time on your mirrorlist - including having an up to date mirrorlist.

I've noticed that since v3.0.0 we might not be performing the speedtest however, so I'm keeping this issue up until I can double check and see what's happening.

**Comment by loxoron218** [comment]
> Technically yes, but we only do it once - right before strapping in your system. `reflector.service` is a good option if you want to maintain a solid performance over time on your mirrorlist - including having an up to date mirrorlist.
> 
> I've noticed that since v3.0.0 we might not be performing the speedtest however, so I'm keeping this issue up until I can double check and see what's happening.

Thanks!

**Comment by svartkanin** [comment]
Somewhere related https://github.com/archlinux/archinstall/issues/2991

The current implementation of the speed test is fragile as it performs these during the menu selection but it does not persist into the configuration files. Obviously storing it in the configuration is complex and a reload would need to recalculate everything.

I'm wondering what the benefit vs maintenance/complexity of this feature is?

@Torxed we may want to consider moving the whole logic to the actual installer that calculates it before starting any downloads

**Comment by Torxed** [comment]
> I'm wondering what the benefit vs maintenance/complexity of this feature is?

It's pretty huge, especially in countries like USA where there's 100+ mirrors but only 10% of those are beneficial at one time depending on where the user is.

> @Torxed we may want to consider moving the whole logic to the actual installer that calculates it before starting any downloads

Yeah, I implemented so that we could use the `sort(key=item.speed)`, but we would have to call that before starting installing. But a better approach would perhaps be `mirrors.sort()` so that we can trigger it whenever we want.

> but it does not persist into the configuration files.

It does'nt need to I think. As mirror performance in of itself is fragile, sorting based on performance is something we need to do every install anyway as it's a moving target.

**Comment by svartkanin** [comment]
https://github.com/archlinux/archinstall/pull/3007 was merged which addressed a different issue but the speedtest for mirrors should work as expected. In that regard I'll close this for now, if there was anything else to do here we can reopen it
