### ISSUE TITLE
Enable resuming/continuing user_interaction information gathering.

### ISSUE THREAD

**Issue by jtagcat** [archlinux/archinstall#330]
![image](https://user-images.githubusercontent.com/38327267/115571315-69532d00-a2ae-11eb-826b-2811cdb87376.png)

This discourages the user, implies disbelief and wastes time. 'Have to start over again.'

**Comment by Torxed** [comment]
There's a catch here, and I think we've discussed this in a previous issue which I can't find right now.
The catch is that deep down inside the profiles, there's no way to "throw back" to a previous prompt *(currently)*.

We could probably detect the `RequirementError` in guided and catch/continue, we can fix that particular issue for this specific menu-entry in the next release. However the overall design issue of "jumping between menu sections" is a bigger/conceptual issue that I'll park for a future version :)

**Comment by jtagcat** [comment]
Since the result is a JSON config, could the information be committed/appended? (git is not installed and imo shouldn't be a (rather large) dependency)

Something like Dockerfile mid-versions  — you should be able to go back, but not forward.  
The forward movement may be done automatically, though — testing additions (and jumping the user to the point of invalid/bad/probably bad step).

~~Getting more advanced, the installation is done in sections (user accounts) and subsections (root pw, new super-user, etc), thus changing something in another category wouldn't re-run everything else.~~ (Not worth the effort of implementing, the installation is small enough, and computers fast enough to just re-run tests.)

**Comment by dylanmtaylor** [comment]
So I think this is mostly fixed in 2.1.4 RC2? Maybe try that out and let us know if it's improved for you.

**Comment by Torxed** [comment]
This was fixed in [v2.1.4](https://github.com/archlinux/archinstall/releases/tag/v2.1.4) *(released yesterday)*. Most menu entries have the ability *(sounds like I'm talking about the future when it's pretty standard)* to loop back when abd input was given. But it doesn't have the ability to jump around in the "menu".

To pause and continue user interaction, you can always use <kbd>Ctrl+z</kbd> to pause a program and `fg` to resume it. So for now I'll consider this fixed until we perhaps re-design the user-interaction all together with a more complex setup.

**Comment by Torxed** [comment]
I should also mention that there is work being done to enable `json` configurations to be injected into archinstall guided to re-run user given configurations for testing. But this will come later.
