### ISSUE TITLE
Add error handling for non-systemd instances (such as docker)

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#351]
As per discussion in the conversation https://github.com/archlinux/archinstall/discussions/347, running in a docker `systemd` and/or `efi` is not always present. In those scenarios it would be nice if we didn't hard crash during normal operation.

As mentioned in the comment https://github.com/archlinux/archinstall/discussions/347#discussioncomment-652837, this will not affect the guided installer - this is an API improvement to support wider .dotfiles and similar runners.

**Comment by dylanmtaylor** [comment]
Who exactly is running an installer in docker? That's typically not how docker is used at all, it's a container, not a virtual machine. What's the use-case here?

**Comment by advaithm** [comment]
I have to agree with @dylanmtaylor supporting containers is something that has not legitimate use case. along with this, containers can not support systemd since they startup in non standard ways and don't even have a kernel. if other distros such as artix want to have archinstall support their system they can fork and maintain their own versions. supporting multiple inits is something that will cause a lot of issues for maintainability

**Comment by Torxed** [comment]
After discussing a bit, we'll table this for now.
Mainly because Arch Linux mainly supports `systemd`, so we'll focus on that as well until further notice.
We've also increasingly integrated systemd services such as `localectl` and `machinectl` for locales and container execution, so it would be hard to get those things working without regression.
