### ISSUE TITLE
Bootloader doesn't install properly

### ISSUE THREAD

**Issue by vessd** [archlinux/archinstall#416]
For some reason, after installation, I don't have any entries in the boot options. 
Executing `bootctl install` manually fixes this issue.
I checked the boot folder before executing, but the `EFI/systemd/systemd-bootx64.efi` and `EFI/BOOT/BOOTX64.EFI` files were in place.

**Comment by Torxed** [comment]
Unfortunately this is an issue due to a workaround introduced to fix a systemd-boot issue back in the days. #350 mentions why and #381 should fix this. So the next release should work a lot better! :)

**Comment by aphirst** [comment]
I am having a similar issue that is not fixed by running `bootctl install` from inside an arch-chroot (where both `/` and `/boot` are mounted).

This is what shows up when I try to boot the UEFI partition, or the Linux Boot Manager, from my motherboard's boot menu:
![error-crop](https://user-images.githubusercontent.com/1735556/117053081-6fb2c180-ad10-11eb-8f2d-e19695373383.jpg)

Install log - [https://paste.rs/UAT](https://paste.rs/UAT)
Another related issue suggested to share my `lsblk -o+PARTUUID,UUID,TYPE,SIZE` output: [https://paste.rs/e6X](https://paste.rs/e6X)
