### ISSUE TITLE
UEFI boot failure when using "minimal" preset, works fine without

### ISSUE THREAD

**Issue by aphirst** [archlinux/archinstall#417]
I'm setting up Arch on a new HTPC build, and I had some time to try out the new installer.

I booted the Arch install ISO (the May 2021 release) from a USB in UEFI mode, and went for what I thought was a straightforward setup, no encryption, on a `Kingston A2000` NVME drive on my `ASRock B450 Pro4 R2.0` motherboard.

When prompted, I chose the `minimal` preset, and presumed that would be the same as simply skipping those presets. I have been informed in IRC (freenode #archinstall) that this is not the case, but one thing at a time. Because I expected/hoped the setup would work, I manually installed a few extra packages before the reboot, including the AMD microcode package.

First install attempt, log: https://paste.rs/UAT
Output of `lsblk -o+PARTUUID,UUID,TYPE,SIZE`:
```
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT            PARTUUID                             UUID                                 TYPE   SIZE
loop0         7:0    0 620.8M  1 loop /run/archiso/airootfs                                                                           loop 620.8M
sda           8:0    1  29.7G  0 disk                                                            2021-05-01-05-18-20-00               disk  29.7G
├─sda1        8:1    1   688M  0 part /run/archiso/bootmnt  31323032-3530-4130-b031-303531383230 2021-05-01-05-18-20-00               part   688M
├─sda2        8:2    1    67M  0 part                       31323032-3530-4130-b032-303531383230 51F2-5358                            part    67M
└─sda3        8:3    1   300K  0 part                       31323032-3530-4130-b033-303531383230                                      part   300K
nvme0n1     259:0    0 465.8G  0 disk                                                                                                 disk 465.8G
├─nvme0n1p1 259:1    0   512M  0 part                       63235116-24dc-40ab-b900-89027e9f79a4 4C99-8A9E                            part   512M
└─nvme0n1p2 259:2    0 465.3G  0 part                       a9d40c3c-7a69-4b67-b032-1fa54715c0a4 2035185d-6afe-4c1d-8b28-cac32cd9c2bd part 465.3G

```
On-screen error when choosing "NVME UEFI" from my motherboard boot menu:
```
EFI stub: ERROR: Failed to open file: boot\amd-ucode.img
EFI stub: ERROR: Failed to load initrd!
EFI stub: ERROR: efi_main() failed!

Failed to execute Arch Linux (\vmlinuz-linux): Not Found
```

I was unable to fix this via simply running `bootctl install` from the install environment or the arch-chroot.

However, if I repeat the install and instead of choosing "minimal", I instead skip that step by pressing Enter, the result seems to be an install that boots without needing to do anything else!

Second install attempt, log: https://paste.rs/z4k

I am going to need to actually use this setup soon, but if it would be helpful, I can do some direct install testing for two or three days. If there's any additional info you need, please do not hesitate to let me know here, or as `aphirst` on freenode.

**Comment by dylanmtaylor** [comment]
Hmm. I've seen this before myself actually. When I looked into it, here's what caused the issue in my case:

After install I re-mounted /mnt and /mnt/boot chrooted in from live media since it did not boot after I started the system up. I looked in /boot in the chroot environment and sure enough the ucode file was not there. After either adding the ucode file to /boot via reinstalling the package or removing the line from the bootloader config file the system started just fine. Still trying to track down that causes this issue, but I THINK that at the time of adding the ucode package (intel, amd, it doesn't matter), the /boot isn't properly mounted so the image file isn't getting written to there.

Worth stating: We are planning on installing ucode for you, for all installations, by default. It's not quite ready yet, but it's tracked in #177. I think this exact issue is the reason it's not part of 2.1.4, but hopefully we'll figure that out by 2.2.0.

**Comment by aphirst** [comment]
I overwrote the install to test without the "minimal" profile, but I am pretty sure that at that time, the microcode file was still present there, as also was the vmlinuz-linux file it complaned was "missing".

**Comment by dylanmtaylor** [comment]
> I overwrote the install to test without the "minimal" profile, but I am pretty sure that at that time, the microcode file was still present there, as also was the vmlinuz-linux file it complaned was "missing".

This is on 2.1.4 on the May ISO? Or are you testing a master build?

**Comment by aphirst** [comment]
I just used the May ISO, yeah. I should have been more specific in my OP.

**Comment by dylanmtaylor** [comment]
No worries, providing all this information is appreciated. I'd try without the ucode packages at install-time and see what happens. I don't think we had any logic to install those or add them to the bootloader in 2.1.4.

**Comment by aphirst** [comment]
I installed those manually before leaving the arch-chroot for the first time, yeah. I'll give the installer another go via the "minimal" profile without adding any other packages, and report back to see whether that fails too, to see whether we can rule out this microcode concern.

**Comment by tmewett** [comment]
I think I'm also getting this issue. After booting several times into my VM just fine, I switched out `linux` for `linux-lts` and now I can't boot.

I notice that on `/dev/sda2` (my `/` partition) I have a `/boot` directory containing the `linux-lts` images. But on `/dev/sda1` (my EFI partition) I also have images. Has something gone wrong with auto-mounting the EFI partition at some point, which has caused pacman to install to a normal directory instead of the EFI partition? Is EFI supposed to even go in `/boot`?

Anyway, I'm going to reinstall without the minimal preset - I think it would be a good idea to mark that as being different somehow to the default, maybe by adding a 'default' option to the list of presets to make it explicit?

**Comment by Torxed** [comment]
> I think I'm also getting this issue. After booting several times into my VM just fine, I switched out `linux` for `linux-lts` and now I can't boot.
> 
> I notice that on `/dev/sda2` (my `/` partition) I have a `/boot` directory containing the `linux-lts` images. But on `/dev/sda1` (my EFI partition) I also have images. Has something gone wrong with auto-mounting the EFI partition at some point, which has caused pacman to install to a normal directory instead of the EFI partition? Is EFI supposed to even go in `/boot`? (EDIT: I actually think that may have been my fault - I think it was before this that I reinstalled `linux` with only `/` mounted so it just stuck the files in there. But it was still not booting before that.)
> 
> Anyway, I'm going to reinstall without the minimal preset - I think it would be a good idea to mark that as being different somehow to the default, maybe by adding a 'default' option to the list of presets to make it explicit?

That would surely explain it, I'm not sure how that issue could pop up - but I'll dig in to it.
I'm also re-working the partitioning logic one final time *(#426)* for the next release which hopefully will avoid issues with mounting/partitioning all together. It's a bit far off tho even for testing sadly. 

When talking about the `minimal preset`, I'm guessing you're referring to the shipped profile called *"minimal"* *(along side desktop etc)* right? If so, I think we should drop that profile to avoid confusion, the default *is* to install the bare minimal, a profile that's called `minimal` just adds confusion. We can set it to a non top level profile perhaps @dylanmtaylor?

**Comment by Torxed** [comment]
> I really like having the minimal profile at the top-level. If you want to just install Arch and nothing else, you need to have that.

I argue the opposite, you can skip the profile selection step, and you end up with the same result.
Unless I've missed something that the minimal profile does?

**Comment by dylanmtaylor** [comment]
Maybe list it as minimal (default)?

**Comment by tmewett** [comment]
The original issue claims there are differences between selecting 'minimal' and skipping the steps:

>When prompted, I chose the minimal preset, and presumed that would be the same as simply skipping those presets. I have been informed in IRC (freenode #archinstall) that this is not the case, but one thing at a time.
> [...]
> However, if I repeat the install and instead of choosing "minimal", I instead skip that step by pressing Enter, the result seems to be an install that boots without needing to do anything else!

I haven't tried to verify this on my end yet. Are you saying that this isn't the case, and that minimal is the exact same as skipping?

**Comment by tmewett** [comment]
My issue is unrelated. I haven't used systemd-boot before and didn't know it didn't auto-generate boot entries like my last set-up did (been a while since my last install...) Sorry for the noise!

**Comment by Torxed** [comment]
> I think I'm also getting this issue. After booting several times into my VM just fine, I switched out `linux` for `linux-lts` and now I can't boot.
> 
> I notice that on `/dev/sda2` (my `/` partition) I have a `/boot` directory containing the `linux-lts` images. But on `/dev/sda1` (my EFI partition) I also have images. Has something gone wrong with auto-mounting the EFI partition at some point, which has caused pacman to install to a normal directory instead of the EFI partition? Is EFI supposed to even go in `/boot`? (EDIT: I actually think that may have been my fault - I think it was before this that I reinstalled `linux` with only `/` mounted so it just stuck the files in there. But it was still not booting before that.)
> 
> Anyway, I'm going to reinstall without the minimal preset - I think it would be a good idea to mark that as being different somehow to the default, maybe by adding a 'default' option to the list of presets to make it explicit?

I'm actually afraid that this is an issue I might have introduced, or at least didn't consider.
I might have accidentally mounted partitions based on their partition order - rather than logical mount positions.
Which means `/boot` can get mounted before `/` and thus making a mess of what is mounted where.

I'll get right on this and fix it. Might be worth a patch release - since this might explain some of the other boot issues, but if I can get `v2.2.0` out in time then that will solve it as well.
