### ISSUE TITLE
Unable set different mount point for partitions

### ISSUE THREAD

**Issue by M4tT3d** [archlinux/archinstall#423]
Hi everyone. When I try to set home as mount point for a partition, the installer stuck in "Select a partition by number that you want to set a mount-point for (leave blank when done):". I can continue the installation only if I set / and /boot as mount point for my partitions. I'm trying to install arch on vBox. Thanks

**Comment by Torxed** [comment]
Hi, just to clarify, did you also set `/` and `/boot`? Since those two are mandatory to continue, they need to be set.
Anything else is optional, such as `/home` - so I just want to make sure you didn't skip the mandatory ones.

**Comment by M4tT3d** [comment]
No. I don't set `/boot` clearly. I want `/` and `/boot` on the same partition and `/home` on a different partition

**Comment by Torxed** [comment]
The current version of archinstall is slightly limited, but the way you would achieve this would be to leave the disk selection blank *(which will force the installer to use `/mnt` as is)*. And set up your partitions (with file systems) before running the installer. That way you can achieve this in the current version.

With that said, the next version will allow you to set this up from within the installer because it will support multiple disk selections as well as multiple partition configurations. Apologies for the inconvenience, we're still improving on the disk selection one iteration at a time - to avoid major issues.

**Comment by M4tT3d** [comment]
ok

> The current version of archinstall is slightly limited, but the way you would achieve this would be to leave the disk selection blank _(which will force the installer to use `/mnt` as is)_. And set up your partitions (with file systems) before running the installer. That way you can achieve this in the current version.
> 
> With that said, the next version will allow you to set this up from within the installer because it will support multiple disk selections as well as multiple partition configurations. Apologies for the inconvenience, we're still improving on the disk selection one iteration at a time - to avoid major issues.

Ok. Thanks for your job

**Comment by joe733** [comment]
Hi, is this fix available in version `2.2.0-1`?
