### ISSUE TITLE
Can not continue with one partition available.

### ISSUE THREAD

**Issue by freehehe** [archlinux/archinstall#460]
when i chosse apply custom partition.i can not go on
![photo_2021-05-17_20-17-14](https://user-images.githubusercontent.com/11854324/118487032-e4dcb880-b74c-11eb-86db-773395621ae0.jpg)

**Comment by Torxed** [comment]
The issue here is that Archinstall can't find a second partition that it supports.
It needs two partitions, one `/boot` and one `/` partition, at least in the current version that is released.

This is because the EFI partition needs to be `fat32` and the root partition can be almost anything.

The next version that's due in a short while will support single-partition-setups with GRUB.
As well as more helpful partitioning guidance.

**Comment by svartkanin** [comment]
@Torxed I reckon this is supported now?

**Comment by svartkanin** [comment]
@Torxed shall we close this?
