### ISSUE TITLE
Boot entries persist even with format all

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#492]
In one of my test VMs I have like 7 boot entries despite choosing the option to format the drive. These should be wiped out if there is only one install on the machine as they use UUID anyways and the older entries will no longer function.

**Comment by Torxed** [comment]
Been discussed in another issue (which I can not find atm).
The main issue is that we don't have a bullet-proof way of reading existing loader entries, detect if they are valid or not - and then take action.

Would love to clean up `/boot`, but I've held off this because I didn't want to possibly remove entries that are still valid on other drives etc. But yes, we need this!

**Comment by Col433** [comment]
Yes this needed to be fixed. While its easy to remove them manually it could confuse new users seeing all the old .conf on booting if they have reinstalled. Of course you could by default comment out the timeout in loader .conf and then they won't see them anyway and boot 3 seconds faster.

**Comment by Torxed** [comment]
I'll add that the new partitioning will 100% guaranteed wipe the drive if this option is selected, which should eradicate any old configurations. This will also wipe dual-boot, but that's the intended use if the drive is selected for a full wipe.
Other options will have to be used in order to supply dual-boot (unless windows boot loader lives on another drive for instance ofc).
