### ISSUE TITLE
Consider using booster as the default initramfs 

### ISSUE THREAD

**Issue by ilyazzz** [archlinux/archinstall#515]
[Booster](https://github.com/anatol/booster) is a simple, but powerful initramfs generator with one of it's key features being support for disk encryption out of the box. It has been in the arch repos for some time now, and I've personally been using it for a while and I'm very happy with it.

The advantages of using it by default would be:
- Not having to do explicit initramfs configuration for disk encryption
- Faster initramfs generation and smaller initramfs images (booster doesn't generate "fallback" full initramfs images by default, only host-specific ones)

A disadvantage would be that booster, being a younger project than mkinitcpio, will have less documentation on the Arch wiki, leaving users more "on their own" for non-standard setups that require additional initramfs configuration.

I think that booster should at least be considered to be an option during installation, even if it doesn't become the default.

**Comment by Torxed** [comment]
I won't reject this further down the line if Arch Linux as a whole goes towards this.
It would solve the issue of Windows creating a very small `/boot` volume. But afaik the preferred method is still `mkinitcpio` *(probably because it's well tested and feature rich)*.

For now, the guided installer will not offer this option as it would go against [Installation Guide#Initramfs](https://wiki.archlinux.org/title/Installation_guide#Initramfs). With that said, we will offer this in the API *(if you script your own installation, even with guided)* through [Plugin support -> on_mkinitcpio()](https://github.com/archlinux/archinstall/pull/393) hooks.

Once Booster becomes more "standard" and a recommendation in the installation guide, I'll re-visit and re-open this *(earlier if we find a clean way of offering both in the API without interrupting guided)*.
