### ISSUE TITLE
How to dual boot with windows 10 in same disk.

### ISSUE THREAD

**Issue by nazar2sfive** [archlinux/archinstall#527]
main disk = /dev/sda

/dev/sda1 = efi
/dev/sda2 = windows 10
/dev/sda3 = free space allocated for arch linux

how to use guided installer to choose /dev/sda3?

**Comment by Torxed** [comment]
Good question, this is one of the remaining issues that I'm trying to work out in #446.
Currently there's two issues:

1. Windows only allocates ~100MB forthe `/boot` partition, in your case `/dev/sda1`. Arch Linux default initramfs is roughly 80MB or so and `mkinitcpio` intalls two initframfs, meaning there's not enough space.
2. archinstall fails to detect free space currently, so it doesn't have a way to create a partition from empty space (oddly enough I forgot this scenario in testing last version).

**Workaround:** Manually create the last partition:
```
fdisk /dev/sda
n
p
<leave rest default>
```
And once that partition is created, add any supported filesystem to it so archinstall allows you to tinker with it *(also a limitation for safety reasons)*:
```
mkfs.ext4 /dev/sda4
```
Once that's done, in archinstall you should be able to use the option *"Re-use partitions"* and select `/boot` for `/dev/sda1` and `/` for `/dev/sda5` and it should allow you to install and dual-boot. It might throw a warning that everything didn't go according to plan, but if that happens just run:
```
arch-chroot /mnt bootctl --path=/boot install
arch-chroot /mnt passwd root
```
And you should have a minimal setup at least.
This workaround won't install profiles and such, but at least give you a working system.

Once #426 is done, this should work much more smoothly, but I need to solve both those problems in order to get dual-boot working, and one issue is slightly out of our control - but we'll try to solve it some how. Resizing partitions is a bit scary so don't know if we can go down that route reliably.

**Comment by mkromar** [comment]
I agree that resizing partitions is a bad idea.

A solution for a small boot partition could be to default to grub, mount ESP to /efi and leave /boot in the rootfs.

**Comment by Torxed** [comment]
> I agree that resizing partitions is a bad idea.
> 
> A solution for a small ESP could be to default to grub, mount ESP to /efi and leave /boot in the rootfs.

This will introduce "unnecessary" complex logic but would solve the problem. *(unnecessary is probably the wrong word here, but couldn't come up with any other phrasing)*.
I would like to stay as true to "do you want X or Y" as possible, by adding checks for size, type and then remove/hide options things get complicated. And technically a small ESP does still work even with systemd-boot, it's just that the fallback image won't be written - but the machine is still bootable.. But because the process fails we fail.
We could instead allow this particular fail to be treated as a "good one" and carry on, assuming at least the main initramfs is written. This would be less complicated and wouldn't break any other logic.. But isn't as clean as what you suggested.

I'm mainly spitting ideas here, not dictating which solution we should go with :)

**Comment by nazar2sfive** [comment]
Can 2 efi exist on same disk? @Torxed

**Comment by Torxed** [comment]
> Can 2 efi exist on same disk? @Torxed

Never heard of it, which either means I or someone I know have never tried it and it does work - or it just doesn't work.
I'm curious so I'll try and see! :)

**Comment by Atomic-Molecule** [comment]
Windows often has the audacity to overwrite boot partitions, or especially EFI ones if it exists on the same drive. This has happened in my personal experience twice and if I could find an article somewhere on why I'd gladly pop it here, so you'd have to take my word for it I suppose

I speculate Windows will clear the other EFI partition _sometimes_ if it detects it as a foreign partition / sector during sanity checks in boot phase. I believe it has little to do with the BIOS as it just reads. It's a risk, and is perfectly repairable because it's just an EFI partition. So yes, they can exist on the same disk, and there's no reason to not have it, but if it's with Windows specifically I'd expect issues.

**Comment by l4zy0n3** [comment]
> > Can 2 efi exist on same disk? @Torxed
> 
> Never heard of it, which either means I or someone I know have never tried it and it does work - or it just doesn't work.
> I'm curious so I'll try and see! :)

I actually had 2 seperate EFI partitions, one for windows and one grub, worked out pretty well.

**Comment by nazar2sfive** [comment]
so in my case where i have manually created my /dev/sda1(efi) of 800MB. guided installer can choose it to install my efi partition.

if in other general case.. where people have 1 laptop (with 1 disk) and they want to dual boot with arch linux as their laptop comes preinstalled with windows 10. in this senario there will be 100MB of efi. in such case guided installer then can create a next efi partition for arch linux from a free space/drive choosen by user to install arch.

**Comment by Torxed** [comment]
Generally the best approach going forward might simply be creating an additional EFI partition (and skip it on GRUB) even tho one exists with Windows-binaries. If not, we can re-use it for multi-linux/bsd setups.

**Comment by Torxed** [comment]
Added a warning when `/boot` is too small.

**Comment by hkaancaliskan** [comment]
Solution to this for what i found in Arch Wiki https://wiki.archlinux.org/title/Dual_boot_with_Windows#Bootloader_UEFI_vs_BIOS_limitations
One of the workarounds is:

> Mount ESP to /efi and use a boot loader that has file system drivers and is capable of launching kernels that reside on other partitions.

Systemd-boot of course can't launch binaries from partitions other than ESP but GRUB can! [Feature_comparison](https://wiki.archlinux.org/title/Arch_boot_process#Feature_comparison)

Also fedora uses this scheme, mounts EFI to /boot/efi and creates a seperate partition for /boot (1gb, ext4). Here is my current lsblk output of Windows11 + Fedora35 dual boot installation: [lsblk.txt](https://github.com/archlinux/archinstall/files/7611999/o.txt)
And also here is my current fstab: [fstab.txt](https://github.com/archlinux/archinstall/files/7612010/fstab.txt)

If user has small EFI and wants dual boot, we can offer this choice.
I think most reasonable workaround is this.
@Torxed what do you think about this?

**Comment by Torxed** [comment]
We've talked about maybe creating additional ESP partitions.
But if ever re-installing Windows on a device that has multiple ESP partitions, at least in the past it has refused to install to such a device. And code-wise we would like to avoid supporting multiple "one offs" and keep GRUB and systemd-boot partition layouts somewhat similar to each other by re-using the same structures and code *(which is one reason why even the GRUB boot loader gets a separate `/boot` partition even tho that's not necessary under MBR for instance)*.

I'm not sure it's possible to do your layout and get it working with both GRUB **and** systemd-boot?

The best option is still that the user manually re-sizes `/boot` to something sane, or that Windows *(and other operating systems)* stop crippling shared spaces such as `/boot`, but I don't see that happening tomorrow.

**Comment by Torxed** [comment]
Closing this since we have a warning for low disk space on `/boot`, and we won't resize it.
But we allow dual-booting if `/boot` is big enough.

**Comment by ImALoooserOk** [comment]
> I'm not sure it's possible to do your layout and get it working with both GRUB **and** systemd-boot?

hi, dropping in to ask, but maybe you could let the user make a [XBOOTLDR](https://wiki.archlinux.org/title/Systemd-boot#Installation_using_XBOOTLDR) partition for `/boot` for systemd-boot and a normal `/boot` partition for GRUB?
