### ISSUE TITLE
Allow retrying package download to improve install process reliability

### ISSUE THREAD

**Issue by mashwell** [archlinux/archinstall#576]
I suggest allowing some way to retry failed package downloads, instead of the current behavior of continuing with the installation process even when `pacman` fails to download a package (leading to a failed installation). This could be caused by intermittent network failures, overloaded package mirrors, etc.

Currently, it is possible to re-launch `archinstall` again and retry the installation process, but the error code it prints before bailing out of the installation process is not that clear (especially if you leave the installation unattended and/or don't scroll up to read the previous log messages :), potentially confusing newbies.

This tends to happen more often when installing bigger DEs and other similarly "huge" packages. The `base` package is less than 200 MB IIRC, and is spread across multiple smaller packages, which makes it much more resilient to failures.

Torxed (via Discord) suggested that instead we only `pacstrap` the core packages (`base` and maybe `base-devel`) and then `arch-chroot` and install the rest of the packages inside that. Maybe with a script that first runs `pacman` with the `--downloadonly` flag, prompts/automatically retry when it fails, and then proceeds to install the packages "for real" if `pacman` exits cleanly.

**Comment by quentincaffeino** [comment]
So I worked on this for a bit because currently I have very unstable connection.

First patch I created follows the OP suggestion by moving everything except base and base-devel to `arch-chroot pacman ...` which came out to be a lot of changes. Which is fine but then I realized that I can just handle network error in pacstrap which is just a few lines change. If process `exit_code` and just restart it as is it seems to run just fine. Because pacstrap always first downloads everything that it hasn't downloaded yet and then runs install process.

I wan't to PR this, which patch would be better? If neither is good why?

If maintainers don't want this then here are both patches for anyone having similar problem (both are based on c6b499cf47fac7a02714e590cf662a85db3095b1)
[chroot_install.diff.tar.gz](https://github.com/archlinux/archinstall/files/7784473/chroot_install.diff.tar.gz)
[chroot_install2.diff.tar.gz](https://github.com/archlinux/archinstall/files/7784474/chroot_install2.diff.tar.gz)

**Comment by Torxed** [comment]
So, we've addressed the unclear error code.
Archinstall will not silently continue any longer since v2.3.1. Instead it will bail out completely.

The diff-files are helpful.
I'll open a PR with them unless someone already has. However, it will take me a bit of time because I'm trying to get v2.3.1 out there asap : )

**Comment by quentincaffeino** [comment]
> I'll open a PR with them unless someone already has.

Thanks, then I guess I will leave this to you as I'm not really sure which of those to pick and if my changes would break something, I'm pretty new to arch.

**Comment by Torxed** [comment]
I would just like to point out that I haven't forgotten about this yet! I'm merging in a bunch of PR's to push forward towards v2.4.0. After all those are in I'll work on some stability improvements and come back to this :)

**Comment by Torxed** [comment]
I made a quick change that enables support for this.
It didn't become as advanced and generic as I would have liked.

But better to get this functionality in there I suppose :)

I'm still inclined to do a `PacMan` class that contextulizes this.
As well as enable the library to expose pacman and pacstrap calls.
But for now this will be fine I think.
