### ISSUE TITLE
Encryption does not seem to work with GRUB.

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#586]
We have multiple users reporting issues using a GRUB bootloader with encryption enabled. I think this is related to the /etc/default/grub file. From what I'm reading on https://wiki.archlinux.org/title/Dm-crypt/Encrypting_an_entire_system#Configuring_GRUB_2 it looks like we need to have `GRUB_ENABLE_CRYPTODISK=y` and `cryptdevice=UUID...` in that config file.

**Comment by Redo11** [comment]
Still broken in 01.09 archiso image

**Comment by dabljues** [comment]
I can confirm, still broken on the newest (01.09) arch image

**Comment by Torxed** [comment]
A few `parted` calls later, and retries on trying to retrieve PARTUUID for partitions *(I really dislike the legacy way the kernel deals with partition information)* it seams I can perform a complete installation at least with GRUB and disk encryption.

However, the boot process still needs to be fixed.
So I'm digging in to how GRUB and encryption works and will tweak the suggested parameters.

![screenshot](https://user-images.githubusercontent.com/861439/142026245-b65c755a-1d5c-4ac7-ab88-8a16b56326d6.jpg)

![screenshot](https://user-images.githubusercontent.com/861439/142026354-eb3e1ee1-6f10-4252-ae36-f5880839fe84.jpg)

**Comment by Ammako** [comment]
Things to keep in mind:

- `grub-install` needs to be called *after* adding `GRUB_ENABLE_CRYPTODISK=y` to the config, otherwise core.img won't know what to do with an encrypted partition.
- Might be worth asking for separate encryption passwords during setup, one for boot and one for root. Users may not necessarily want the same for both, especially if you're using luks1 for /boot and luks2 for root.
- For ease of use, I suggest to generate a keyfile for /boot (readable only by root! set permissions appropriately), store it on root partition, and edit crypttab to use the keyfile instead of prompting for a password. This should be reasonably secure because the keyfile can never be accessed without first decrypting the root partition anyway, and it'll avoid having to enter /boot decryption password twice.

**Comment by Torxed** [comment]
> Things to keep in mind:
> 
> * `grub-install` needs to be called _after_ adding `GRUB_ENABLE_CRYPTODISK=y` to the config, otherwise core.img won't know what to do with an encrypted partition.
> * Might be worth asking for separate encryption passwords during setup, one for boot and one for root. Users may not necessarily want the same for both, especially if you're using luks1 for /boot and luks2 for root.
> * If you're using luks2 for /boot, the process is [a little different](https://wiki.archlinux.org/title/GRUB#LUKS2) right now.
> * For ease of use, I suggest to generate a keyfile for /boot (readable only by root! set permissions appropriately), store it on root partition, and edit crypttab to use the keyfile instead of prompting for a password. This should be reasonably secure because the keyfile can never be accessed without first decrypting the root partition anyway, and it'll avoid having to enter /boot decryption password twice.

That is some solid advice. This will take me a day or two to wrap my head around as I never use GRUB personally. But I'll update here and/or the PR.

**Comment by Torxed** [comment]
![image](https://user-images.githubusercontent.com/861439/142080054-dd2eeb57-1f68-426e-89ab-a206c95eda3e.png)

I'm not sure what's changed since GRUB + Encryption worked *(or if it ever worked)*, but this command fails: https://github.com/archlinux/archinstall/blob/a18a652bb0557c0dae7c5706893efd3a217c6598/archinstall/lib/installer.py#L625

**Comment by Ammako** [comment]
You install on /dev/sda, not /dev/sda1, for what it's worth

**Comment by Torxed** [comment]
I think the disk alignment is off? There's not enough room before `/dev/sda1`? Or at least that's what I gathered from [GRUB2](https://wiki.gentoo.org/wiki/GRUB2/Troubleshooting) docs.

**Comment by Torxed** [comment]
Disk related issues are fixed I believe in #724.
First partition start sector has moved up from 1MiB to 5MiB.
One issue remains, and that is that we don't and shouldn't use a separate `/boot` partition when using GRUB, as pointed out by @Ammako. It completely slipped my mind that you didn't use a separate boot partition back in the days *(since you only have space for 4 partitions it would be a huge waste to reserve one for `/boot`)*. This is something we'll have to re-visit and come back to and see if we can figure out a clean way of implementing partition-elimination if GRUB on BIOS is selected, and in other cases keep it for the standard disk layout.

For stability reasons, I won't try to sort that out because then v2.3.0 will never be released.

* [x] Encryption with GRUB is fixed *(now installing to ´/dev/sda` instead of `/dev/sda1`)*
* [x] Partitioning issues related to UUID's and PARTUUID's appears to be solved with `parted`, sleep and retries on `Partition.uuid` as well as partitioning operations.

I there for think the PR is ready for a merge and this issue to be solved and closed.
But I would like to thank every single one who's contributed to information on this topic.

![screenshot](https://user-images.githubusercontent.com/861439/142217300-2031034f-9cc4-40cf-bf5b-97af97c1409e.jpg)

**Comment by Ammako** [comment]
The disadvantage with leaving /boot on the same partition as root is that root has to inherit the weaker encryption required by grub. The partition limit is an issue for sure, but I'd suggest at least leaving separate /boot partition as an option.

That still leaves enough room for a separate home partition + a data or windows partition, and if someone really needs another partition on top of that, they can opt to leave /boot on root.

**Comment by Torxed** [comment]
> The disadvantage with leaving /boot on the same partition as root is that root has to inherit the weaker encryption required by grub. The partition limit is an issue for sure, but I'd suggest at least leaving separate /boot partition as an option.
> 
> That still leaves enough room for a separate home partition + a data or windows partition, and if someone really needs another partition on top of that, they can opt to leave /boot on root.

Fair point!

**Comment by Torxed** [comment]
PR is merged, up to 95% of all issues should be resolved now.
I'll begin the process of creating v2.3.0-RC2 and focus on the remaining dead code paths before release.

**Comment by HanM23** [comment]
Done an installation today with /boot/efi fat32 partition, / btrfs with 2 sub and luks encrypted.
Installation is OK
But when i boot up, i got the following issue :

![image](https://github.com/archlinux/archinstall/assets/38059479/565808bb-3976-44c7-adbd-548235178193)

the uuid in the picture exists, this is the uuid of the decrypted root partition e.g. /dev/mapper/xxxxxx

When i edit the grub menu i have the following :+1: 

![image](https://github.com/archlinux/archinstall/assets/38059479/d16b64f9-f88f-4e96-aae1-6fffa7e2229e)

Is it a bug or do i have an issue with my system ?
Thanks
