### ISSUE TITLE
Missing user directories

### ISSUE THREAD

**Issue by Radioactive92177** [archlinux/archinstall#594]
So I recently switched from **Manjaro** to **Vanilla Arch** and I couldn't bear the fact that it doesn't make **user directories** automatically.
I had to install **xdg-user-dirs** , and run **xdg-user-update** to make it work.
I believe it should be included in the default packages of the guided installer.

**Comment by liuhaowen478** [comment]
I agree that this should happen by default on desktop profiles.

**Comment by Torxed** [comment]
I'm open to the idea of an optional installation of `xdg-user-dirs` if a desktop environment is selected.
I personally don't like to clutter down the disk with folders that I'll never use.

```
XDG_DESKTOP_DIR="$HOME/Desktop"
XDG_DOCUMENTS_DIR="$HOME/Documents"
XDG_DOWNLOAD_DIR="$HOME/Downloads"
XDG_MUSIC_DIR="$HOME/Music"
XDG_PICTURES_DIR="$HOME/Pictures"
XDG_PUBLICSHARE_DIR="$HOME/Public"
XDG_TEMPLATES_DIR="$HOME/Templates"
XDG_VIDEOS_DIR="$HOME/Videos"
```

Out of all these, I think I would only use `Downloads` because the browsers use it by default.
But if people really use all these and want them (a majority of users), then I'd be open to adding a **optional**  question to create these directories after a desktop profile was chosen. So feel free to submit a PR and I'll go through it and merge it if it looks clean :)

**Comment by nerdyman** [comment]
I realised that the scripts don't create a home directory for the user specified in the config which stumped me for a few hours when trying to get a Pantheon desktop set up working as LightDM immediately logs out if the user's home directory isn't there. It would be useful for the `/home/<user>` directory to be created per user specified in the config (even if the XDG dirs aren't included).

**Comment by svartkanin** [comment]
I believe this is created in the latest version

**Comment by Torxed** [comment]
>  It would be useful for the `/home/<user>` directory to be created

This should definitely be the case, as it's done via `-m` when `useradd` is called: https://github.com/archlinux/archinstall/blob/15e52b77683f266ee843def2bb35ed02cd8e559d/archinstall/lib/installer.py#L1198-L1203

```
-m, --create-home             create the user's home directory
```

**Comment by svartkanin** [comment]
Fantastic thanks for clarifying
