### ISSUE TITLE
Need a longer timeout when formatting

### ISSUE THREAD

**Issue by andbenn** [archlinux/archinstall#620]
My decade plus old laptop, which has a slow rotating hard drive, needs more than 10 seconds I think.

The archinstall script bombs out when formatting and partitioning:

New partition never showed up after adding new partition for Filesystem (blockdevice=BlockDevice(/dev/sda), mode 2) (timeout 10 seconds)

Just after the countdown, my drive starts spinning and I see the light on.  10 seconds pass, and this exception with that message.  I'm pretty sure aged hard disks will need more than 10 seconds at this step.

idea: make the timeout configurable for those with SSD, desktop harddrives, and laptop harddrives.
I'd be OK with a timeout of 60 seconds or so.  10 seconds is kind of short.

When installing another Linux distro, in this case Ubuntu, formatting takes about 25 seconds on this laptop.  I think a 30-40 second timeout might be appropriate.

**Comment by Torxed** [comment]
We've got a flag for hardware type in the upcoming merge into master.
It also has some features to wait and detect partitions when they show up.

I'm eager to test those changes, since hopefully the "wait until the partition is probe:able" should deal with this things dynamically. But I haven't tested it on older hardware.

**Comment by andbenn** [comment]
Sounds promising and looking forward to trying it again.  Could you let me know when this is in the ISO I can download and I'll make another attempt?  Much appreciated!
