### ISSUE TITLE
Unable to set locale 'us' for console: Failed to get shell PTY: No machine 'archinstall' known

### ISSUE THREAD

**Issue by huoi** [archlinux/archinstall#633]
![image](https://user-images.githubusercontent.com/59074303/133245858-73cb9f12-00fd-4857-aea8-8fccd5435c31.png)

`/var/log/archinstall/install.log`:

![VirtualBox_Base Arch_14_09_2021_17_58_45](https://user-images.githubusercontent.com/59074303/133246036-a9b07075-ea2c-4ba2-a73b-94cac197767e.png)
![VirtualBox_Base Arch_14_09_2021_17_59_10](https://user-images.githubusercontent.com/59074303/133246045-fc29cdb8-7875-4b6b-9824-16f2e42e1764.png)

**Comment by Torxed** [comment]
This usually happens when packages failed to install.
The row `Could not strap in packages: 256` indicates that installing individual packages failed.

I've (last night) added a hard exception that will break the installed if this happens.

**Comment by Torxed** [comment]
The commit 168379d should make this more clear, and increase error verbosity.
And it also adds a exception which should prohibit the installer from continuing.. Avoiding these kinds of issues.

It will however mean that the install will break mid-way, rather than trying to continue as long as possible - leaving less things to clean up on errors. But the good outweighs the bad here.
