### ISSUE TITLE
ArchInstall should expose a flag to install a system with testing repo enabled

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#686]
For trying things out on non-production machines with the testing repository, it'd be neat to be able to do a full system install with the unstable packages available in testing in a VM by doing something like `archinstall --testing`. This would simply make sure that this repository is not commented out in /etc/pacman.conf:

```
[testing]
Include = /etc/pacman.d/mirrorlist
```

Probably a low-priority feature request, but a nice to have.

**Comment by OpenSourceAnarchist** [comment]
I think this would be a great feature, and hopefully could be a part of #814.

For example, a new function, something like `custom_repos()` could replace `add_custom_mirrors` in `mirrors.py` and take as parameters: A list/dict in the same format as used by `add_custom_mirrors`, an option to choose prepending or appending to the mirror definitions in `/etc/pacman.conf`, and a boolean specifying whether the custom mirror definitions should be copied to the installed system (defaults as true). In the case of [testing], this could be a special case where the definition is uncommented rather than prepended (since it's already defined by default).
