### ISSUE TITLE
[2.3.0-RC1] Automatic partitioning does not fill drive with btrfs and no encryption

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#696]
![btrfs-layout](https://user-images.githubusercontent.com/277927/140819976-069c8282-4fcb-4498-8f69-5a1e3e4a996c.png)

[My installation log](https://github.com/archlinux/archinstall/files/7500204/install.log.txt)

**Comment by Torxed** [comment]
As discussed in discord, this is due to the elif: https://github.com/archlinux/archinstall/blob/68a1e42cfeed4c8986e7fb42330aefeb9a772710/archinstall/lib/disk/user_guides.py#L61

It doesn't get triggered when using subvolumes. The precious if block shluld increase root volume to 100% and use subvolumes
