### ISSUE TITLE
Very low inode count in created F2FS filesystem

### ISSUE THREAD

**Issue by OJFord** [archlinux/archinstall#771]
I created my F2FS filesystem with archinstall, and after some moderate docker use for a few weeks began seeing 'out of space' errors with around 700GB (of 1TB) remaining.

An easy way to reclaim some space was to `docker system prune`, unfortunately it only occurred to me to check afterwards, but subsequently the vast majority of used inodes are in `/var/lib/docker/overlay2`, and overall:
```console
arch-f2fs$ df -i /
Filesystem           Inodes   IUsed   IFree IUse% Mounted on
/dev/mapper/luksdev 9784317 5694170 4090147   59% /
```

Presumably this is just the default (I can't see otherwise) but I think it would be helpful for archinstall to change, considering it's not readily fixable later as F2FS partitions cannot be shrunk.

My colleagues with APFS systems (and similarly 1TB) have vastly more to begin with:
```console
mac-apfs$ df -i /
Filesystem     512-blocks     Used  Available Capacity iused      ifree %iused  Mounted on
/dev/disk3s1s1 1942700360 30672696 1443541576     3%  575614 4293938969    0%   /
```

Their `(575614 + 4293938969) /` my `9784317 = 439`.

I seem to have about 104,622 `bytes-per-inode`, I believe the ext4 default is 16,384; maybe this larger value makes particular sense for Android  (or the smaller storage devices typical there) but I'd suggest lowering it for `archinstall`.

**Comment by Torxed** [comment]
We'll have to do some fine tuning when setting up f2fs: https://github.com/archlinux/archinstall/blob/c4ba14e62a0c8d78f11413f19cdea552e2c5419a/archinstall/lib/disk/partition.py#L306-L311

Is this related to the amount of updates, and if so what they reference to as [wandering tree problem](https://www.kernel.org/doc/html/v5.7/filesystems/f2fs.html#wandering-tree-problem)? Or if this is bad defaults on f2fs side of things, maybe it's worth reporting upstream?

By default it seams f2fs allocated [4KB per inode](https://www.kernel.org/doc/html/v5.7/filesystems/f2fs.html#index-structure).

**Comment by OJFord** [comment]
Thanks for your reply. The 'wandering tree problem' sounds like it's about write performance, the speed of making all the necessary updates when a file is updated (moved in the log structure)?

And thanks for the pointer to `inline_data`, unfortunately it's already in use though (not something I changed post install) - mount options in `/etc/fstab` are:
```
rw,relatime,lazytime,background_gc=on,discard,no_heap,inline_xattr,inline_data,inline_dentry,flush_merge,extent_cache,mode=adaptive,active_logs=6,alloc_mode=default,checkpoint_merge,fsync_mode=posix
```

I think that 4KB is the 'inode size' in `mkfs` parlance right? Not the addressable space left over (after `inode-size * num-inodes`) divided by 'num inodes', which is what I meant (and again `mkfs` term I believe) by 'bytes-per-inode'.

**Comment by Torxed** [comment]
You're probably right. I know to little about f2fs specifically to question more or less anything you say hehe. But yes the 4KB should be `inode-size`. And `num-inodes` should be `block-device-size / inode-size` minus any directory entries *(dentry)* for the inodes themselves. in f2fs that seams to be 11 bytes per entry.

I'm not sure I understand the core issue of the problem well enough other than the default `mkfs.f2fs -i 104622` is the culprit here, not something we set. `archinstall` supports overriding the defaults through:

```json
{
    "options": ["-i", "16384"],
    "filesystem": {
        "format": "f2fs"
    }
}
```
In the `--disk_layouts` structure *(Previously found in `--config`)* when deploying with a JSON configuration.
It's also scriptable through your own .py installations, but not something we offer through the guided process as it's a bit too advanced as of now.

There's probably a reason why f2fs has this default in their `mkfs.f2fs` package, and I think it's better to report this issue upstream and tweak that number if it's a general issue for everyone. It's hard for us to address this without going from "sane defaults" if that's what it is.

**Comment by OJFord** [comment]
I had another look at this just now installing a new system - it seems F2FS allocates inode blocks dynamically; `mkfs.f2fs`'s `-i` option is different to `ext4`'s:

> -i extended node bitmap, node ratio is 20% by default

Which I don't really understand (does extended mean some arbitrary number greater than 20? Do I supply a percentage?) and I can't find more information on it, but it's different.

I'm not sure why I ran out, but it seems not an issue/fixable here.
