### ISSUE TITLE
ZRAM swap issue from reddit

### ISSUE THREAD

**Issue by psyfry** [archlinux/archinstall#782]
A user posted about an issue with archinstall on Reddit, not sure if they have a github account, so copying it here for them.

===================================
**Archinstall script on latest 2021.12.01 iso is a bit broken**

So decided to use archinstall script again for giggles and ran into a bunch of issues:

When not selecting zram swap and selecting the option to optimally format it is called 0 now,it still creates 3 partitions for some weird reason and one of them for a whooping 20GB and ads like 3 free space partitions in between,looks like this in cfdisk:

free space

/dev/sda1

free space

/dev/sda2

free space

/dev/sda3

2. Also there is no option to create root and user with superuser(sudo) privileges anymore only one or another which is not secure/weird decision?

3. Still present from previous version,even if you don't choose to install NVIDIA drivers you still get the weird Wayland session on top of X11 in KDE Plasma,which is obviously borked on NVIDIA.

4. Once the zram swap partition or whatever it is,is created the entire root/main user directory is put on these 20GB so you are out of luck if you try to install a bunch of dependencies/packages that are more than 20GB in size

Anyway, it is all curable by a manual Arch Linux installation,but still the previous version of archinstall was better,this one is weird.Hope this helps anyone who decides to use archinstall to speed things up,that is not the case anymore.

==============================

Another user's response to above post:
I don't have the zram issue, but I do have the free space thing. 5MB free, 500MB FAT partition, 5MB free, then 1000GB BTRFS. Also agree with the user thing, weird decision to remove that. I made a post about how to deal with that, but it ended up getting downvoted because I may or may not have introduced a small security issue by giving root to anyone who knows the root password... I was a bit slow to figure out that I needed to uncomment out the sudo and wheel group before adding a user to the groups.

**Comment by Torxed** [comment]
Good feedback. Did the user by any chance post the log files? Especially the install.log?

**Comment by fkortsagin** [comment]
Hello!
archinstall.log pastebin
https://pastebin.com/ACBsGyXy
pacman log in case it is needed:
https://pastebin.com/ZxgWqngV
And we will probably need to open another issue for the swap space being used as main root/sudoer /mnt point and not using the home directory.Low disk space:
https://ibb.co/3YB1fR1
cfdisk result after archinstall the mnt point is located on the 18 GB instead of 70GB Home,same results on HW testing:
https://ibb.co/LCNfKHW

**Comment by fkortsagin** [comment]
> ~Good feedback. Did the user by any chance post the log files? Especially the install.log?~
> 
> I found the post and saw that they did not. I've asked in a DM for the file, in case there's a copy. Would help or speed up the debugging process a tiny bit :)

Hello!
archinstall.log pastebin
https://pastebin.com/ACBsGyXy
pacman log in case it is needed:
https://pastebin.com/ZxgWqngV
And we will probably need to open another issue for the swap space being used as main root/sudoer /mnt point and not using the home directory.Low disk space:
https://ibb.co/3YB1fR1
cfdisk result after archinstall the mnt point is located on the 18 GB instead of 70GB Home,same results on HW testing:
https://ibb.co/LCNfKHW

**Comment by Torxed** [comment]
> > ~Good feedback. Did the user by any chance post the log files? Especially the install.log?~
> > I found the post and saw that they did not. I've asked in a DM for the file, in case there's a copy. Would help or speed up the debugging process a tiny bit :)
> 
> Hello! archinstall.log pastebin https://pastebin.com/ACBsGyXy pacman log in case it is needed: https://pastebin.com/ZxgWqngV Another issue for the swap space being used as main root/sudoer /mnt point and not using the home directory.Opened here: #784 Video of the whole archinstall with issues described: https://www.reddit.com/user/silentgameplayz/comments/r74qr2/archinstall_script_issues/?utm_source=share&utm_medium=web2x&context=3

Great work on collecting as much detail as possible. I'll start working on a fix soon.

**Comment by fkortsagin** [comment]
Thank you for the feedback! Always happy to help out!

**Comment by Torxed** [comment]
The 5MB free spaces in between is due to bad math on my part: https://github.com/archlinux/archinstall/blob/3ef83873fbf9c6edd6fa4f26b93087e42e378f30/archinstall/lib/disk/user_guides.py#L81

I was trying to compensate for previous partitions being created.
There doesn't seam to be any issues tied to swap reading the logs and the comments.
It's mostly about the weird free space and root being 20GB, and the 20GB thing has been tweaked slightly in 3ef8387.
That fix will be out in v2.3.1 coming days.

For the future, I'll some how squeeze in a question if a separate `/home` partition is even desired.
I thought there was a consensus within the community that it should be a sane default - but a lot of people object. So we'll have to divide into two options here.

**Comment by fkortsagin** [comment]
T

> The 5MB free spaces in between is due to bad math on my part:
> 
> https://github.com/archlinux/archinstall/blob/3ef83873fbf9c6edd6fa4f26b93087e42e378f30/archinstall/lib/disk/user_guides.py#L81
> 
> I was trying to compensate for previous partitions being created in MB and the new ones being in GB, but parted seams to be using MiB even if you specify MB, so I'll have to fix that. There doesn't seem to be any issues tied to swap reading the logs and the comments. It's mostly about the weird free space and root being 20GB, and the 20GB thing has been tweaked slightly in [3ef8387](https://github.com/archlinux/archinstall/commit/3ef83873fbf9c6edd6fa4f26b93087e42e378f30). That fix will be out in v2.3.1 coming days.
> 
> For the future, I'll some how squeeze in a question if a separate `/home` partition is even desired. I thought there was a consensus within the community that it should be a sane default - but a lot of people object. So we'll have to divide into two options here.

/home is usually default for the main user and root,it is logical,but when you have like a limit of 20GB for the main user OOTB that is just enough for the OS install with KDE,if you go full blown gaming and actual usage it is not enough,yeah I mean you can go around it by spending a bunch of time in fstab/gparted tweaking,but the goal of the arch installscript is to make it as simple as possible.
For users that object it is possible to just add an option to customize the partittioning scheme like "Something else",the default should be the way it is 512MB UEFI and rest is for the main user/root.

**Comment by Torxed** [comment]
> the default should be the way it is 512MB UEFI and rest is for the main user/root.

I'm inclined to agree. The benefits of having a separate `/home` doesn't outweigh the problems it creates.
And users that do know what they're doing and really want a separate `/home` can do so by running `--dry-run` and modify `/var/log/archinstall/user_disk_layouts.json` to add in a `/home`.

If no one objects, I'll remove the additional `/home` logic or put it behind a question. But I'd like to minimize questions at this point.

**Comment by fkortsagin** [comment]
> And users that do know what they're doing and really want a separate `/home` can do so by running `--dry-run` and modify `/var/log/archinstall/user_disk_layouts.json` to add in a `/home`.

Agreed,there can be a built in option for customize partitioning scheme for these users,but generally it is more logical and secure to have the default root and main user separated in general,but they both should have access to the main /home path,otherwise its tweaking time all the time.
Also using either main sudoer user or root is also a not very secure idea,by default the less a person uses root for everything the better,there is a sudo command for that.
Root should exist,but for emergencies only in case it is required to troubleshoot/recover the main user or multiple user accounts.

**Comment by Torxed** [comment]
I'm closing this for now so it's easier for me to track what issues remain for v2.3.1, as the general issue is kinda fixed.
I've started a discussion on discord *(and comments on this thread is welcome)* about removing `/home`. Most people are on vacation now tho so the discussion might drag out a bit.
