### ISSUE TITLE
Wrong mount options in /etc/fstab when installing with F2FS 

### ISSUE THREAD

**Issue by rowheel** [archlinux/archinstall#798]
To reproduce: Just issue a fresh install with F2FS as the filesystem format.

Some redundant mount options in /etc/fstab, likely to be directly copied from that of ext4's, are not existing for f2fs, and they will prevent mounting the local disk on the first boot.

**Comment by dylanmtaylor** [comment]
Which options do you believe to be problematic?

**Comment by das-rob3rt** [comment]
> Which options do you believe to be problematic?

Just wait a few more hours - I will post a log after I get my hands at the keyboard 🙏

**Comment by das-rob3rt** [comment]
So I issued a fresh install, and selected f2fs as the filesystem

![PXL_20211213_121337371.jpg](https://user-images.githubusercontent.com/29014642/145810620-0754504b-ed01-420a-9c85-41f459e5a218.jpg)

After I reboot it says this option was not recognized

![PXL_20211213_121422822.jpg](https://user-images.githubusercontent.com/29014642/145810628-9c45d353-7f1b-4c2c-a478-e0312fcf66e1.jpg)

So after I edited that, it says this option was also not recognized

![PXL_20211213_121453361.jpg](https://user-images.githubusercontent.com/29014642/145810607-b3b7da6c-2161-49d5-9123-38bb11b93219.jpg)

And cleared both shall I enter the login prompt.

**Comment by Torxed** [comment]
What does your `/etc/fstab` look like?

**Comment by das-rob3rt** [comment]
> What does your `/etc/fstab` look like?

Hi, just wait a few more hours - I'm on my way home 🏠

**Comment by das-rob3rt** [comment]
> What does your `/etc/fstab` look like?

Sorry for hanging you there, the `/etc/fstab` now looks something like this (after getting both of the problematic mount options removed):

```
# Static information about the filesystems.
# See fstab(5) for details.

# <file system> <dir> <type> <options> <dump> <pass>
# /dev/nvme0n1p2
UUID=REDACTED	/         	f2fs      	rw,relatime,lazytime,background_gc=on,discard,no_heap,inline_xattr,inline_data,inline_dentry,flush_merge,extent_cache,mode=adaptive,active_logs=6,alloc_mode=default,fsync_mode=posix	0 0

# /dev/nvme0n1p1
UUID=REDACTED      	/boot     	vfat      	rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro	0 2

# /dev/nvme0n1p3
UUID=REDACTED	/home     	f2fs      	rw,relatime,lazytime,background_gc=on,discard,no_heap,inline_xattr,inline_data,inline_dentry,flush_merge,extent_cache,mode=adaptive,active_logs=6,alloc_mode=default,fsync_mode=posix	0 0
```

**Comment by Torxed** [comment]
We generate default options for fstab via `genfstab`, so I'm wondering what the faulty options where, how they got there and if this is a generic issue that maybe should be reported upstream?

**Comment by das-rob3rt** [comment]
> We generate default options for fstab via `genfstab`, so I'm wondering what the faulty options where, how they got there and if this is a generic issue that maybe should be reported upstream?

As shown in the above pictures, the faulty options were `checkpoint_merge` and `discard_unit=block`, which have already been removed from my `/etc/fstab` in order to get a bootable system.

And yes - if we generate via `genfstab` then we might need to report this to the upstream. Afterall, I guess not many people nowadays still use `f2fs`, are there?  lol

**Comment by Torxed** [comment]
> > We generate default options for fstab via `genfstab`, so I'm wondering what the faulty options where, how they got there and if this is a generic issue that maybe should be reported upstream?
> 
> As shown in the above pictures, the faulty options were `checkpoint_merge` and `discard_unit=block`, which have already been removed from my `/etc/fstab` in order to get a bootable system.
> 
> And yes - if we generate via `genfstab` then we might need to report this to the upstream. Afterall, I guess not many people nowadays still use `f2fs`, are there? lol

Hehe, I think it's still a very unpopular file system *(that's not the same as it's not being used and liked by the ones that do, just that it's not a majority)*. Which is why perhaps we haven't seen many bug reports of issues with it on a wider use.

We don't do anything specific unless you submit options to our `Partition().format()`: https://github.com/archlinux/archinstall/blob/3c2e71b4bbfa2168afb54eb70aeecce9064c8435/archinstall/lib/disk/partition.py#L307-L312

I'd recommend to report this upstream, and we'll close this issue once they've fixed it.
That way we can track it here as well for our own sanity.

**Comment by das-rob3rt** [comment]
> Hehe, I think it's still a very unpopular file system *(that's not the same as it's not being used and liked by the ones that do, just that it's not a majority)*. Which is why perhaps we haven't seen many bug reports of issues with it on a wider use.
> 
> We don't do anything specific unless you submit options to our `Partition().format()`: https://github.com/archlinux/archinstall/blob/3c2e71b4bbfa2168afb54eb70aeecce9064c8435/archinstall/lib/disk/partition.py#L307-L312
> 
> I'd recommend to report this upstream, and we'll close this issue once they've fixed it.
> That way we can track it here as well for our own sanity. When reporting, don't forget to include your hardware specifications as it's relevant to them.

We might not be aware of it, but we are very lilely already using it - if you have a recent Android phone, then you may see its `data` partition is formatted as `f2fs`.

![Screenshot_20211214-230859~2.png](https://user-images.githubusercontent.com/29014642/146024738-ec67f125-35c6-4463-9db2-5f27ab7a4359.png)

I actually believe `f2fs` is flash friendly (as its name suggests) and can provide fine tuned performance for SSDs or flash storage kinds of storage devices, but few people use it on their PCs. Probably that's because distros like Rocky or Debian won't even bother to provide this fs as an option, and I am very happy to see `archinstall` do. 😂

**Comment by svartkanin** [comment]
I believe this should be fixed by now, if not we can reopen it
