### ISSUE TITLE
Use pacman's --needed argument to avoid reinstalling packages

### ISSUE THREAD

**Issue by lan-vuhoang** [archlinux/archinstall#800]
1. Automatically use `reflector` to select the best mirrors instead of having you manually select countries when your country doesn't necessary has the best mirrors available. Or just allow you to selecting multiple countries to use.
2. Enable `pacman`'s newly added parallel downloads feature.
3. Use `pacman`'s `--needed` argument to avoid reinstalling packages like `grub` when unnecessary.

**Comment by Torxed** [comment]
> 1. Automatically use `reflector` to select the best mirrors instead of having you manually select countries when your country doesn't necessary has the best mirrors available. Or just allow you to selecting multiple countries to use.

We already use reflector if you skip this step.
It's described in the [docs](https://archinstall.readthedocs.io/en/latest/installing/guided.html#mirror-region-selection) *(this can be made more clear in the archinstall TUI as well)*

> 2. Enable `pacman`'s newly added parallel downloads feature.
We already use this, since we don't change the default pacman configuration.
So whatever the default pacman settings are in the ISO, we use those.

> 3. Use `pacman`'s `--needed` argument to avoid reinstalling packages like `grub` when unnecessary.
This we could add : ) I welcome a PR, should be an easy fix.
