### ISSUE TITLE
Using custom repos with installed system

### ISSUE THREAD

**Issue by OpenSourceAnarchist** [archlinux/archinstall#814]
I would like to use archinstall, but initially use and get packages from the unofficial ALHP repos (see https://git.harting.dev/ALHP/ALHP.GO & https://wiki.archlinux.org/title/unofficial_user_repositories#ALHP). Since these are custom, optimized builds of Arch Linux official packages, the custom repos need to be added to `/etc/pacman.conf` _before_ the declarations for [core], [extra], and [community], because the official repositories need to be a lower priority and only used as a fallback. I know there is a function, `add_custom_mirrors()`, that allows for _appending_ custom repos to `/etc/pacman.conf`, but that is only for the live ISO, I believe, and will therefore not be carried over to the installed system. Additionally, it only supports appending custom mirrors/repos, rather than supporting both prepending and appending.

There are many reasons advanced users may want to have unofficial/custom repositories as sources for their installation, for example if they want to have packages from them automatically installed, or in my case, to override the official package versions. In many cases, these custom repositories should be carried-over to the installed system in the created `/etc/pacman.conf` file (I think this is the best default behavior), though an option should allow for them to not be carried-over.

I am fully aware that _specific_ custom repositories are not supported or endorsed, but giving the option for users to add them should not be a problem, I hope. Otherwise, I would have to install Arch Linux using the official packages... just to have to re-install everything again after adding them myself, which really doesn't make any sense if my goal is to use custom package builds. This change would also allow specifying and using _official_ repositories such as testing, gnome-unstable, kde-unstable, etc. Any repositories (name, URL/Include (mirrorlist), SigLevel) could be added and optionally preserved on the installed system.

**Comment by Torxed** [comment]
I personally don't see why we can't support this.
The only danger would be people putting in custom mirrors and then asking for help in support channels. But as long as this is not default behavior and triggered by command arguments instead of something inside `guided.py`, I think it should be fine.

It won't be a priority for me to code on this, but I'd welcome a PR to support it.
Something like:
```
archinstall --mirrors https://git.harting.dev/ALHP/ALHP.GO,https://git.harting.dev/ALHP/ALHP.GO.TESTING
```
Would perhaps work?
And that should omit: https://github.com/archlinux/archinstall/blob/638a05243c7bab7db7449c24a2ab770e581244d0/examples/guided.py#L82-L83

And we'd have to figure out a way to set it in https://github.com/archlinux/archinstall/blob/638a05243c7bab7db7449c24a2ab770e581244d0/examples/guided.py#L273-L274

And in https://github.com/archlinux/archinstall/blob/638a05243c7bab7db7449c24a2ab770e581244d0/examples/guided.py#L278-L279

I also see this as a great benefit for offline environments where this has been a drag for myself for quite some time. Even with an officially synced repository mirror, the only way to get it working have been to point DNS records, [patch archiso](https://github.com/Torxed/archoffline) or to manually edit `/etc/pacman.d/mirrorlist` before running. This would make it slightly more convenient to run against offline targets and custom ones :)

**Comment by AladW** [comment]
> triggered by command arguments instead of something inside guided.py

Yes, this definitely does not belong in the guided installer, unless you want to go down the path of unsupported installers which include their own repos. 

If you're going to add flags like `--mirrors` anyway, they should be listed in `archinstall.log` as well.

**Comment by Torxed** [comment]
> If you're going to add flags like `--mirrors` anyway, they should be listed in `archinstall.log` as well.

It's technically already possible.
Just that it's a bit more hassle. And yes, any alterations we do are logged in the log as well as the `user_configuration.json` :)

But I don't see why it has to be unsupported, I for instance have a offline synced mirror to offload servers. I'd like to use that one. Official packages and synced like any of the official one :)

**Comment by TheLinuxNinja** [comment]
Being able to specify a specific mirror would be huge. We use internal mirrors for Arch and other distros, so the ability to point to an internal mirror instead of an external one is VERY important for us (even though our mirrors are of only the official packages). This way, we can stand up test Arch VMs in a matter of only a couple of minutes, based on disk speed.

**Comment by svartkanin** [comment]
Custom mirrors/repos are available in the installer
