### ISSUE TITLE
Luks.add_key waits forever and some questions about key-files

### ISSUE THREAD

**Issue by wllacer** [archlinux/archinstall#817]
I'm trying to setup an encrypted partition using keyfiles (with the *generate-encryption-key-file* parameter) but it waits forever at the generating step of this key files. According to htop, the cryptsetup addKey command exists but not consuming any cpu. Probably it is waiting for the password
Just reading it again i know why 
https://github.com/archlinux/archinstall/blob/c6b499cf47fac7a02714e590cf662a85db3095b1/archinstall/lib/luks.py#L156-L171
You are searching for a string in English at line 165 and my system spits it out in Spanish :-(((. 
Won't happen on an installation disk but might do elsewhere.

I have also a couple of questions around the key-files which are making my life difficult on my btrfs efforts (as a matter of fact is the only important roadblock i'm having now), but more on this later. Do you happen to have some documentation about the current implementation of them?

**Comment by wllacer** [comment]
I've found a workaround using SysCommand. I am not so sure it is the best solution, but does allow me to continue my research (i don't want to go into the rabbit hole of SysCommand* right now)
Instead of 
```
		#worker = SysCommandWorker(f"/usr/bin/cryptsetup -q -v luksAddKey {self.partition.path} {path}")
		#pw_injected = False 
                ...
```
I send. 
```
		if (handle := SysCommand([f"/usr/bin/cryptsetup -q -v luksAddKey {self.partition.path} {path} <<EOF" ,  f"{password}" , "EOF"]).exit_code != 0:
		  raise DiskError(f'Could not add encryption key {path} to {self.partition} because: {b"".join(handle)}')
```
NOTE that the content of SysCommand is a LIST not a string

**Comment by Torxed** [comment]
We've had issues elsewhere regarding locales, so I'm pretty confident this exists in other places too. Although we don't wait for stdout output in a lot of places. A more long term fix would be to somehow grab the translated locale of the expected string. But I'm not sure if it's possible to query the language files of the application.

**Comment by wllacer** [comment]
I think i do have a solution, even more, a general solution.
After a couple of false leads I learned (read ' lots of googleing) that on the command line, locale can be changed for the execution of a single command prefixing it with LC_ALL=C.
On my system
```
[root@xerneas archinstall]# /usr/bin/cryptsetup -q -v luksAddKey /dev/loop0p2 /mnt/archinstall/etc/cryptsetup-keys.d/ainst_loop0p2loop.key
Introduzca cualquier frase contraseña que exista: 
...
[root@xerneas archinstall]# LC_ALL=C /usr/bin/cryptsetup -q -v luksAddKey /dev/loop0p2 /mnt/archinstall/etc/cryptsetup-keys.d/ainst_loop0p2loop.key
Enter any existing passphrase: 
...
[root@xerneas archinstall]# 
```
 No. It does not work adding it into the SysCommandWorker command string. It's a bit more subtle. SysCommand* admits as a named parameter a dict of environment variable. I tried it and it (seems) works at last
```
        worker = SysCommandWorker(f"/usr/bin/cryptsetup -q -v luksAddKey {self.partition.path} {path}",
environment_vars={"LC_ALL":"C"})
```
But, what is better, injecting this entry into the initialization of SysCommandWorker would make it general and transparent for ALL the commands we are executing inside the application, no matter where executed.
I'll make a PR with this solution (if a couple of test runs don't show up any other problems) so you can test it.

**Comment by wllacer** [comment]
PR number is #827

**Comment by Torxed** [comment]
That's a pretty neat fix for the issue. As long as we don't do this for output that the user expects to be translated *(not in this case for instance)* that would probably be the best way forward.

**Comment by wllacer** [comment]
The trick with the environment variable works fine in this case. I will use it for my next batch of code, till we take a decision on a more global solution (as in the PR)
OTOH it still hangs sometimes. Very hard to reproduce, because always a restart has worked flawlessly for me. Maybe in certain cases *cryptsetup* sends some intermediate message ¿? 
Can we extend the usage of *cmd_output.txt* beyond the "pacman" steps of the procedure? And switch it "on the fly"?  Haven't looked at it but in a cursory way

**Comment by Torxed** [comment]
> Can we extend the usage of _cmd_output.txt_ beyond the "pacman" steps of the procedure?

I'm ok with adding more things too it.
I think all output from `SysCommand*` should be there tho, so that is if you want to add other command outputs there too, that should be fine :)

**Comment by JonasMayerDev** [comment]
Hello, I had the same problem as @wllacer with each of my installation attempts, that adding the key took infinitely long. 
I'm not that familiar with the script yet but for me it worked with a simple os.system() call:  
``` python3
def add_key(self, path :pathlib.Path, password :str):
		if not path.exists():
			raise OSError(2, f"Could not import {path} as a disk encryption key, file is missing.", str(path))

		log(f'Adding additional key-file {path} for {self.partition}', level=logging.INFO)
		import os 
		log(f'Run os.system', level=logging.INFO)
		ret = os.system(f"echo '{password}' | /usr/bin/cryptsetup -q -v luksAddKey {self.partition.path} {path}")
		log(f'os.system ret code: {ret}', level=logging.INFO)

		worker = SysCommandWorker(f"/usr/bin/cryptsetup -q -v luksAddKey {self.partition.path} {path}")
		pw_injected = False
		while worker.is_alive():
			log(f'Stuck here', level=logging.INFO)
			log(f'{worker}', level=logging.INFO)
			if b'Enter any existing passphrase' in worker and pw_injected is False:
				worker.write(bytes(password, 'UTF-8'))
				pw_injected = True

		if worker.exit_code != 0:
			raise DiskError(f'Could not add encryption key {path} to {self.partition} because: {worker}')
```

Is there a special reason (e.g. regarding security) not to do this with os.system()?


Here is my output with this new code (I used "test" as the password).

![Bildschirmfoto_2022-01-04_06-50-07](https://user-images.githubusercontent.com/43114340/148016461-0d7cacdd-02ba-4e37-a8bc-9d35093dbb8d.png)

You can see my os.system() call works as it should. Even if I left out the SysCommandWorker completely in another attempt (so that the installation doesn't hang) I can decrypt the disk with my password again...
What I find a bit strange is that as I understand it, the worker doesn't fail to recognize the correct string, since it writes (at least as it seems) the password ("test"). This would mean, if I'm not mistaken, that the error in this case is not due to the system language or the returned string from cryptsetup, right?
Maybe this will help to track down the problem. I would be very happy about an answer!

**Comment by wllacer** [comment]
@JonasMayerDev . Many thanks for your input. I assume that you are working in a native english locale. 

Did you try the same command you launched with os.system,  under SysCommand* (commenting out everything from after the call till the check of the exit code ? I didn't tried the trick with the pipe, very smart

SysCommand* end up executing os.execve() which is a very different animal to os.system(). For Archinstall purposes, it's enough to know that os.system() does not give the level of control of the executing task, our program needs to solve.  Which does not mean , it can not be used, once in a while, as a workaround, as long as one only cares for the exit code ;-)

But what wonders me is that you say it always happens to you with the SysCommandWorker interface. My experience is that this block of the process, once i solved the localization problem, happens only sporadically. Your output looks like cryptsetup is blocked and not consuming the input (the password) and that is unsettling

**Comment by Torxed** [comment]
I think I've found one reason for the sporadicness.
I think I've glued the cache together in an odd way.
It's regarding the way we look for a newline. I'll see if I can dig a bit more.

**Comment by JonasMayerDev** [comment]
Hi, I have to retract my earlier statement. I seem to have had only bad luck. When testing it now I think it also ran once with the old SysCommandWorker command.  
I also assumed that I use English as my system language, since I use the standard iso of arch linux.  The only thing I changed is that I changed my keyboard layout to german. (Could this cause a problem with the write?). When I run cryptsetup -q -v luksAddKey ... ... manually in the console, the correct english string is output.

![Bildschirmfoto_2022-01-04_20-50-06](https://user-images.githubusercontent.com/43114340/148119869-828b13ce-4133-4f0e-b02e-4983d79d5c47.png)

I have now also run the new command with the pipe through the SysCommandWorker class, but it seems that the class does not yet support multiple commands in one call, since (see output) apparently everything after the "echo" is seen as an argument... That was my code and the output of it. 

``` python3
def add_key(self, path :pathlib.Path, password :str):
		if not path.exists():
			raise OSError(2, f"Could not import {path} as a disk encryption key, file is missing.", str(path))

		log(f'Adding additional key-file {path} for {self.partition}', level=logging.INFO)
		log(f"Executing: echo '{password}' | /usr/bin/cryptsetup -q -v luksAddKey {self.partition.path} {path}", level=logging.INFO)
		
		worker = SysCommandWorker(f"echo '{password}' | /usr/bin/cryptsetup -q -v luksAddKey {self.partition.path} {path}")
		#pw_injected = False
		while worker.is_alive():
			log(f"still alive: {worker}", level=logging.INFO)
		#	if b'Enter any existing passphrase' in worker and pw_injected is False:
		#		worker.write(bytes(password, 'UTF-8'))
		#		pw_injected = True

		if worker.exit_code != 0:
			raise DiskError(f'Could not add encryption key {path} to {self.partition} because: {worker}')
		
		log(f"Finished executing: echo '{password}' | /usr/bin/cryptsetup -q -v luksAddKey {self.partition.path} {path}; with worker: {worker}", level=logging.INFO)
```
![Bildschirmfoto_2022-01-04_21-04-43](https://user-images.githubusercontent.com/43114340/148119943-b8dc91eb-326e-49f9-a46c-9a30be642749.png)


Maybe this is intentional but it seems to me that this is still a bug? 

In any case I put the new command in a bash -c " " to avoid this "problem". See new code:

``` python3
def add_key(self, path :pathlib.Path, password :str):
		if not path.exists():
			raise OSError(2, f"Could not import {path} as a disk encryption key, file is missing.", str(path))

		log(f'Adding additional key-file {path} for {self.partition}', level=logging.INFO)
		log(f"Executing: bash -c \"echo '{password}' | /usr/bin/cryptsetup -q -v luksAddKey {self.partition.path} {path}\"", level=logging.INFO)
		
		worker = SysCommandWorker(f"bash -c \"echo '{password}' | /usr/bin/cryptsetup -q -v luksAddKey {self.partition.path} {path}\"")
		#pw_injected = False
		while worker.is_alive():
			log(f"still alive: {worker}", level=logging.INFO)
		#	if b'Enter any existing passphrase' in worker and pw_injected is False:
		#		worker.write(bytes(password, 'UTF-8'))
		#		pw_injected = True

		if worker.exit_code != 0:
			raise DiskError(f'Could not add encryption key {path} to {self.partition} because: {worker}')
		
		log(f"Finished executing: bash -c \"echo '{password}' | /usr/bin/cryptsetup -q -v luksAddKey {self.partition.path} {path}\"; with worker: {worker}", level=logging.INFO)

```


Now it seems to work perfectly for me...
First it gives this output here: 
![Bildschirmfoto_2022-01-04_21-14-25](https://user-images.githubusercontent.com/43114340/148120039-c3952c81-41e9-4973-99d0-352976aab0a4.png)

And after a bit of waiting (and being spammed :)) it gives this output:   
![Bildschirmfoto_2022-01-04_21-15-42](https://user-images.githubusercontent.com/43114340/148120054-d5c582dc-0338-4abb-85f0-9e8c147f35ac.png)

Hope this helps and thanks for the answer :)

**Comment by JonasMayerDev** [comment]
I've now done some more googling and have come up with this probably somewhat safe version of my approach. The problem before was that if the password is included in plain text in the command to start a new process, theoretically any user on that system could read it. See this output, which additionally uses 
``` python3 
os.popen(f "ps aux | grep {password} | grep -v grep").read()
```
to search for processes with the password:
```
still alive: b'', processes that show password: root       31305  0.0  0.0   7256  2940 pts/185  Ss+  01:26   0:00 /usr/bin/bash -c echo 'the_password!' | /usr/bin/cryptsetup -q -v luksAddKey /dev/sda3 /mnt/archinstall/etc/cryptsetup-keys.d/mntloop.key

still alive: b'', processes that show password: root       31305  0.0  0.0   7256  2940 pts/185  Ss+  01:26   0:00 /usr/bin/bash -c echo 'the_password!' | /usr/bin/cryptsetup -q -v luksAddKey /dev/sda3 /mnt/archinstall/etc/cryptsetup-keys.d/mntloop.key

still alive: b'', processes that show password: root       31305  0.0  0.0   7256  2940 pts/185  Ss+  01:26   0:00 /usr/bin/bash -c echo 'the_password!' | /usr/bin/cryptsetup -q -v luksAddKey /dev/sda3 /mnt/archinstall/etc/cryptsetup-keys.d/mntloop.key
```

The new version just calls sh (not bash, since bash has a history that would be awkward to disable) (which is then the only thing to see with ps) and writes the command to the existing sh process with worker.write(). The new code and the output looks like this:

```python3
def add_key(self, path :pathlib.Path, password :str):
		if not path.exists():
			raise OSError(2, f"Could not import {path} as a disk encryption key, file is missing.", str(path))

		log(f'Adding additional key-file {path} for {self.partition}', level=logging.INFO)
		log(f"Executing: echo '{password}' | /usr/bin/cryptsetup -q -v luksAddKey {self.partition.path} {path}", level=logging.INFO)
		
		worker = SysCommandWorker(f"/usr/bin/sh")
		pw_injected = False
		while worker.is_alive():
			out = os.popen(f"ps aux | grep {password} | grep -v grep").read()
			log(f"still alive: {worker}, processes that show password: {out}", level=logging.INFO)
			
			if pw_injected is False:
				worker.write(bytes(f"echo '{password}' | /usr/bin/cryptsetup -q -v luksAddKey {self.partition.path} {path}; exit $?", 'UTF-8'))
				pw_injected = True

		if worker.exit_code != 0:
			raise DiskError(f'Could not add encryption key {path} to {self.partition} because: {worker}')
		
		log(f"Finished executing: echo '{password}' | /usr/bin/cryptsetup -q -v luksAddKey {self.partition.path} {path}; with worker: {worker}", level=logging.INFO)
```

```
still alive: b"\x1b[?2004hsh-5.1# echo 'the_password!' | /usr/bin/cryptsetup -q -v luksAddKey /dev/sda3 /mnt/archinstall/etc/cryptsetup-keys.d/mntloop.key; exit\r\n\x1b[?2004l\r", processes that show password: 
still alive: b"\x1b[?2004hsh-5.1# echo 'the_password!' | /usr/bin/cryptsetup -q -v luksAddKey /dev/sda3 /mnt/archinstall/etc/cryptsetup-keys.d/mntloop.key; exit\r\n\x1b[?2004l\r", processes that show password: 
still alive: b"\x1b[?2004hsh-5.1# echo 'the_password!' | /usr/bin/cryptsetup -q -v luksAddKey /dev/sda3 /mnt/archinstall/etc/cryptsetup-keys.d/mntloop.key; exit\r\n\x1b[?2004l\r", processes that show password: 
```

**Comment by Torxed** [comment]
I'm closing this as we've introduced forcing locale to `C` :)
If there's still an issue I'm happy to re-open.
