### ISSUE TITLE
Low disk space in the filesystem root

### ISSUE THREAD

**Issue by AndreaMonzini** [archlinux/archinstall#837]
Hello
i receive often the warning with "low disk space in the filesystem root"
Indeed the root has less than 1 GB of free space and i tried to clean the cache with "sudo pacman -Scc"

I installed the system ( release 2022.01.01 ) on the 500 GB SSD  with ext4 and GNOME and the root partition is 19 GB while the Home is 480 GB.

Could  be useful to add the option to select the size of partitions ?
Other suggestions?
Thank you !

**Comment by Torxed** [comment]
This has been fixed in `master` and tweaked in `v2.3.1` which is bound to be released in a few days.
`master` will ask if you want to create a separate `/home` and if so, create a `60G` partition for `/` instead of the current `20` *(which I thought was generous heh)*.

So I'll go ahead and close this one as it's already fixed. But thank you for reporting this, and to track some other questions you can check this issue:

**Comment by dylanmtaylor** [comment]
> This has been fixed in `master` and tweaked in `v2.3.1` which is bound to be released in a few days. `master` will ask if you want to create a separate `/home` and if so, create a `60G` partition for `/` instead of the current `20` _(which I thought was generous heh)_.
> 
> So I'll go ahead and close this one as it's already fixed. But thank you for reporting this, and to track some other questions you can check this PR: #801

We should probably prompt for root size

**Comment by Torxed** [comment]
> We should probably prompt for root size

Not a bad idea, we'll correct that in `master`.
I want to avoid touching `v2.3.1` too much.
