### ISSUE TITLE
Defaults to English, even if chosen otherwise

### ISSUE THREAD

**Issue by Patrxgt** [archlinux/archinstall#875]
Like in the title, when I choose Polish, Arch generates only English locale, so whole system is defaulted to English after installation.

**Comment by Torxed** [comment]
Is this in `master` or one of the stable releases?
I know we still have this in `master` and will be fixed before release :)

**Comment by Patrxgt** [comment]
I had this problem on the newest Arch Linux ISO.

**Comment by Torxed** [comment]
> I had this problem on the newest Arch Linux ISO.

I understand, then this should be fixed in the next release :)

**Comment by Patrxgt** [comment]
I want to report, that even in the newest release installer defaults to English, even if chosen otherwise.

**Comment by Torxed** [comment]
I did not make it in time for the ISO release, but we'll look in to it.

**Comment by Patrxgt** [comment]
Thank you

**Comment by svartkanin** [comment]
I tried to reproduce this but it worked fine for me using `master`.

**Comment by Patrxgt** [comment]
Well, it doesn't work too well for me on newest Arch Linux ISO.

**Comment by Torxed** [comment]
I suspect it's the system language in question?
Because keyboard locale works, but perhaps the system language isn't Polish?

**Comment by Patrxgt** [comment]
Yup, system is still in English. It also chooses US keyboard no matter what.

**Comment by svartkanin** [comment]
Hmmm my system language went to German the locale de_DE though.

Just to make sure @Patrxgt did you actually restart or just chroot into it? Because I think chroot didn't work for me either only when rebooting into the actual new system they were applied

**Comment by hexarch** [comment]
![image](https://user-images.githubusercontent.com/96956419/157344432-2f3f654e-c0bd-462f-ada9-422598dcd0c3.png)
![image](https://user-images.githubusercontent.com/96956419/157344470-c8a8f859-552d-441b-87d6-8994420baca6.png)
I always choose PT keyboard as above and language is always en_US because I don't see where you can choose the language on the script. But it sets the keyboard correctly for my keyboard.
I don't use another language for the operating system but if I wanted to change, I always do it on the desktop environment later, as the other locale settings. 
So the question says "when I choose Polish, Arch generates only English locale" and are you choosing the keyboard and expecting it to default locales to the chosen keyboard language?

**Comment by Torxed** [comment]
We haven't implemented a language menu yet, due to the fact that it's been hard to cramp that in to the old menu system. Also listing of available languages isn't/wasn't straight forward.

You can override the **system** language by running `archinstall --advanced` or `archinstall --sys-language en_PL.UTF-8` to set it directly.

**Comment by Torxed** [comment]
New menu system allows for UI language of archinstall.
As well as a more intuitive way of setting keyboard layout.

The UI language will only reflect archinstall.
If archinstall is started with `--advanced` you also get the option to set system UI language as well as encoding.

The `--advanced` selection of locale and encoding is also searchable, which helps a lot.
