### ISSUE TITLE
[Feature Request] Add option to install AUR helper

### ISSUE THREAD

**Issue by Patrxgt** [archlinux/archinstall#876]
It would be nice, if installer could install AUR helper, like pamac, yay or paru and give a choice between those three.

**Comment by Torxed** [comment]
This is one is the only one I don't think we can budge on.
Due to support reasons and Arch Linux officially not supporting anything AUR-related *(even your entire installation would be more or less unsupported)*.

However, you can do `archinstall --plugin=https://raw.githubusercontent.com/Torxed/archinstall-aur/main/archinstall_aur/__init__.py` and it would source it and use the AUR plugin.

**Note:** Again, you know the drill surrounding support. And the plugin isn't really fully developed yet.. But the concept holds true! :)
