### ISSUE TITLE
Could not get PARTUUID

### ISSUE THREAD

**Issue by uhthomas** [archlinux/archinstall#892]
Not really sure why, the command works fine when run manually.

![image](https://user-images.githubusercontent.com/9749173/150665621-e1b45ffe-9172-45b0-afb2-d5f0f4462022.jpeg)

**Comment by Torxed** [comment]
This should be fixed in master after we moved from lsblk to blkid

**Comment by uhthomas** [comment]
I believe this was master (see 2.3.1dev0 from screenshot).

I could be wrong, though.

**Comment by Torxed** [comment]
2.3.1 is a separate branch :) and is based on v2.3.0. I'll verify this in master but should be fixed. Unless we forgot lsblk somewhere

**Comment by uhthomas** [comment]
I've just tried again and I'm pretty sure I wasn't using master. I'm happy to close if this is believed to have been fixed.

**Comment by Torxed** [comment]
I'll leave it open for a bit longer. It shouldn't happen in v2.3.1dev0 either, so I'll probably pull in the `blkid` changes from `master` in to `v2.3.1` so we sort that out properly.

**Comment by Torxed** [comment]
This should now be fixed in in both `master` and `v2.3.1` (See https://github.com/archlinux/archinstall/pull/901 for details on the change).

I haven't tested with a loop device yet, but using `blkid` should be more reliable and not produce this issue any longer.
I'd be happy to re-open if it still occurs.
