### ISSUE TITLE
Missing method in deferred translation

### ISSUE THREAD

**Issue by wllacer** [archlinux/archinstall#966]
Testing the menu, I selected profile > desktop > budgie and got (really for xorg profile)
```
  File "/home/werner/projects/archinstall/archinstall/lib/menu/selection_menu.py", line 617, in _select_profile
    with profile.load_instructions(namespace=namespace) as imported:
  File "/home/werner/projects/archinstall/archinstall/lib/profiles.py", line 137, in __exit__
    raise args[1]
  File "/home/werner/projects/archinstall/archinstall/lib/menu/selection_menu.py", line 618, in _select_profile
    if not imported._prep_function():
  File "/home/werner/projects/archinstall/archinstall/profiles/desktop.py", line 58, in _prep_function
    with profile.load_instructions(namespace=f"{desktop}.py") as imported:
  File "/home/werner/projects/archinstall/archinstall/lib/profiles.py", line 137, in __exit__
    raise args[1]
  File "/home/werner/projects/archinstall/archinstall/profiles/desktop.py", line 60, in _prep_function
    return imported._prep_function()
  File "/home/werner/projects/archinstall/archinstall/profiles/budgie.py", line 26, in _prep_function
    with profile.load_instructions(namespace='xorg.py') as imported:
  File "/home/werner/projects/archinstall/archinstall/lib/profiles.py", line 137, in __exit__
    raise args[1]
  File "/home/werner/projects/archinstall/archinstall/profiles/budgie.py", line 28, in _prep_function
    return imported._prep_function()
  File "/home/werner/projects/archinstall/archinstall/profiles/xorg.py", line 28, in _prep_function
    archinstall.storage["gfx_driver_packages"] = archinstall.select_driver()
  File "/home/werner/projects/archinstall/archinstall/lib/user_interaction.py", line 925, in select_driver
    title += _('For the best compatibility with your Intel hardware, you may want to use either the all open-source or Intel options.\n')
TypeError: can only concatenate str (not "DeferredTranslation") to str

```
@svartkanin Seems the DeferredTranslation would profit from, at least an \__add\__ method ("string" concatenation in this case)
Just for reference [magic methods](https://docs.python.org/3/reference/datamodel.html). Thought I think to add them when they are needed is more sensible

**Comment by svartkanin** [comment]
Ahh yes, in the past I did a simple `str(...)` however that's quite a lazy workaround since all new usages will break.
So I definitely agree to implement a __add__ there as well. I thought about going through the magical ones but then decided to opt for implement when needed, not too overload things too much in the class. 

I'll fix this tomorrow morning!

**Comment by wllacer** [comment]
> Yeah this is probably also due to the DeferredTranslation object being used, I'll try to find a generic solution for this one as well

It has a simple solution in this case. As it will happen in Menu, it's relatively simply (a map statement) to change in the options list a Deferred Translation to its DeferredTranslation.str(). I will try it and report results

**Comment by wllacer** [comment]
Works, but ...
I'm not that much partial to the idea of having localized strings at the config file (I'd even suppress the `archinstall-language` entry when saving the config.file). In this case we were lucky, because the localized string (['nic']['nic']) is a noop for the network configuration in this case, and a language change did not impact this.
I'll change to string only in the `ask_for_network` to keep the program from failing, and if necesary in other modules as well, till we decide what we do with localization and menu values. @Torxed, what do you think about this ?

**Comment by svartkanin** [comment]
@wllacer I've raised https://github.com/archlinux/archinstall/pull/976

To the first issue mentioned, implementing a `__add__` in the `DeferredTranslation` class will prevent some errors from happening but not all of them related to concatenation. E.g. for the exact issue above that didn't quite solve it, the reason for that is that when doing 
```
'i am a string' + DeferredTranslation(...)
```
then the __add__ of the string class is called not the one from DeferredTranslation. To solve it completely I had to transform the initial string also into a DeferredTranslation object. This means that any future implementations where someone tries to concat a `str + DeferredTranslation` will still break and I'm not sure if that's preventable except for testing ones code before pushing :) 

To the second problem, I have transformed the objects now into strings before sending them off to `Menu(...)`. In addition I've also added a check in the Menu class to verify that all passed options are actual strings, this was mainly to display a more explicit error what the problem is. I'm not to keen on doing any mapping `obj -> str` in the Menu class, because that would essentially erase the contract we created in the interface which specifies that we are only excepting strings as options.
