### ISSUE TITLE
Rework the network configuration

### ISSUE THREAD

**Issue by svartkanin** [archlinux/archinstall#991]
As discussed with @Torxed and @wllacer we'll update the network configuration to a single type and include type specific configuration as a subelement of the data structure. I'll have a look at this soon and will keep the backwards compability (which we put in with the prev PR already) in place, unless we want to only support the new configuration?

**Comment by Torxed** [comment]
Perfect, thanks!

**Comment by svartkanin** [comment]
What's the best way to document them?

**Comment by Torxed** [comment]
> What's the best way to document them?

I will put it in the release notes, currently the format for v2.4.0 is:

---------

# Breaking Changes

 * `archinstall.SysCommand*` now properly raises exceptions when exit codes are bad. This used to go by unnoticed in some cases, which caused silent errors. The flip-side to this is that it may now be overly aggressive and cause breakage at certain points. In which case the call itself should be wrapped around a catch block. As an example:
   ```python
   if (result := archinstall.SysCommand("ls --breaking-arguments")).exit_code != 0
   ```
   Should now be:
   ```python
   try:
       result = archinstall.SysCommand("ls --breaking-arguments")
   except SysCallError as error:
       if error.exit_code != 0:
   ```
   This avoids the risk of calls silently passing errors.
 * `archinstall.Filesystem().load_layout()` now looks for the keyword `"wipe": True` and not `"format": True`. This is to avoid confusion as to what the menu alternatives does, for instance *"mark partition for wiping"* as well as avoid mixing up the format options like `"filesystem"` and other options during formatting.

# New Features

 * A completely new menu system *(still accessibility friendly)* using [simple-term-menu](https://github.com/IngoMeyer441/simple-term-menu) as the base *(bundled with this source to avoid external dependencies. A big thank you to Ingo Meyer and his employer at the time)*:
   ![screenshot](https://user-images.githubusercontent.com/861439/152638047-abe56543-b109-4e7e-96e4-3e973c56c9fa.jpg)
 * Localization/Translation options for all archinstall output *(Currently `us`, `es` and `se` is available)*. To contribute please read the [translation contribution README](https://github.com/archlinux/archinstall/blob/f6d133804b7fdfab5a00d95a1985c3e220935ac1/archinstall/locales/README.md)

# Minor changes and bug fixes

 * `archinstall.define_arguments()` has been added to separate the logic of setting up `ArgumentParser` arguments.
 * Fixed all arguments so that they support both `--x="something"` and `--x "something"`.
 * Typing has been added throughout archinstall

---

And so on : ) This is just a small snippet of like 200 changes that will land in v2.4.0, small and big :)
There's 6 breaking changes of varying size at the moment. If you summarize it similarly in the PR that will be good enough or I can write something up :)

**Comment by svartkanin** [comment]
@Torxed I think we can close this one as well?

**Comment by Torxed** [comment]
PR should have done it with the keywords hehe
